cypress-autorecord-tests
saltastroops/web-manager pull request #130
Opened 2022-07-12 13:21 UTC by mofokeng-chaka

Auto record Cypress tests

2022-07-12 19:02 UTC, hettlage requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: all files reviewed, 19 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/integration/authentication.spec.ts` line 33 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nUrN35FvfP18H6j67:-N6nUrN553yUWVYiu1vE:b-xxfjxr) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/authentication.spec.ts#L33)):*
> ```XML
>       LoginPage.visit();
>       LoginPage.login(USERNAME, password);
>       cy.wait(`@${alias}`);
> ```

Can't you just use a "unique" string?

My concern is that effectively you make the test more complicated than necessary.

(The same comment applies to the other test functions and files, of course.)
___
*[`cypress/integration/forgot-password.spec.ts` line 76 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nVo1-E6WS_yTIMDdf:-N6nVo1-E6WS_yTIMDdg:b-ihzrjo) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/forgot-password.spec.ts#L76)):*
> ```XML
>   });
> 
>   // eslint-disable-next-line @typescript-eslint/ban-ts-comment
> ```

Are these comments necessary before the it() ?
___
*[`cypress/integration/login.spec.ts` line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nW9t863jsIG4Mo0DF:-N6nW9t863jsIG4Mo0DG:b-ssfy9g) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/login.spec.ts#L27)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(path.join(apiUrl, "**")).as(alias);
> ```

Wouldn't that join with a backslash on Windows?
___
*[`cypress/integration/navigation-bar.spec.ts` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nWk4A3uvqIK_S4XrY:-N6nWk4A3uvqIK_S4XrZ:b-ssfy9g) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/navigation-bar.spec.ts#L32)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(path.join(apiUrl, "**")).as(alias);
> ```

Wouldn't that join with a backslash on Windows?
___
*[`cypress/integration/navigation-bar.spec.ts` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nXMOk4YmGldjEDvkT:-N6nXMOl8W54L-V0LJC8:bkyalt5) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/navigation-bar.spec.ts#L32)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(path.join(apiUrl, "**")).as(alias);
> ```

I'm a bit concerned (here and everywhere else) that you record an authentication token.
___
*[`cypress/integration/home/home-user.spec.ts` line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nY7Yu6v9fc2ICUCym:-N6nY7Yu6v9fc2ICUCyn:bq9y7xo) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L35)):*
> ```XML
>   });
> 
>   it.only("should show an alert regarding the hard limit", () => {
> ```

There should be no "only".
___
*[`cypress/integration/home/home-user.spec.ts` line 383 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYdaa88TgU-eU_bpR:-N6nYdaa88TgU-eU_bpS:bigrkn) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L383)):*
> ```XML
>   });
> 
>   it("should show principal contact's proposals", () => {
> ```

Is this really for the Principal Contact only?
___
*[`cypress/integration/home/home-user.spec.ts` line 389 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYmOR8-oi5ovmkiAR:-N6nYmOR8-oi5ovmkiAS:b-hq0j1u) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L389)):*
> ```XML
> });
> 
> // eslint-disable-next-line @typescript-eslint/ban-ts-comment
> ```

Are these comments necessary?
___
*[`cypress/integration/home/home-user.spec.ts` line 418 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYrGW2t7eHV3LpyRt:-N6nYrGW2t7eHV3LpyRu:b-u7th99) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L418)):*
> ```XML
>   });
> 
>   it("should show astronomer's proposals", () => {
> ```

Is this really for the astronomer? If you don't like "my", maybe use "user's"?
___
*[`cypress/integration/proposal/block-summaries.spec.ts` line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nZFjH4jUadLn7yNww:-N6nZFjH4jUadLn7yNwx:bgyyfed) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/proposal/block-summaries.spec.ts#L18)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord("http://127.0.0.1:8001/**").as(alias);
> ```

Hardcoding this URL seems incorrect. (The same applies everywhere else where this might be done.)
___
*[`cypress/plugins/index.ts` line 91 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nloT699SwipJa6cjo:-N6nloT699SwipJa6cjp:b95f176) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/plugins/index.ts#L91)):*
> ```XML
> 
>     /**
>      * Read file.
> ```

Read file with JSON content and return its content as an object.

(And maybe the name should be something like readJsonFile?)
___
*[`cypress/plugins/index.ts` line 105 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6ndOHK9cWIAYJ1N8Uz:-N6ndOHK9cWIAYJ1N8V-:buz8w6l) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/plugins/index.ts#L105)):*
> ```XML
>     createDirectory(filePath: PathLike) {
>       if (!fs.existsSync(filePath)) {
>         fs.mkdirSync(filePath);
> ```

Don't you have to use the `recursive` option?
___
*[`cypress/support/commands.ts` line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nfGgv07sihxca02fA:-N6nfGgv07sihxca02fB:b-u9ys3z) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/support/commands.ts#L18)):*
> ```XML
>     } else {
>       request.continue((response) => {
>         intercepts[key] = JSON.stringify(response);
> ```

Does this really store the value?
___
*[`cypress/support/index.ts` line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nepZs4bQXYOTYKMYz:-N6nepZs4bQXYOTYKMZ-:boj2ysb) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/support/index.ts#L41)):*
> ```XML
> afterEach(() => {
>   // The replace fixes Windows path handling
>   const fixturesFolder = Cypress.config("fixturesFolder")
> ```

I'm not convinced this should be done... (possibly applies everywhere else as well).
___
*[`cypress/support/index.ts` line 55 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6neiGB3OCWHWM5Yh9U:-N6neiGB3OCWHWM5Yh9V:bxymfrk) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/support/index.ts#L55)):*
> ```XML
>     (responses: { [key: string]: string }) => {
>       if (Object.getOwnPropertyNames(responses).length !== 0) {
>         cy.wait(`@${alias}`)
> ```

Where is this alias coming from?
___
*[`cypress/support/index.ts` line 59 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6neG7G4E5dE92g19tG:-N6neG7G4E5dE92g19tH:b [...]

2022-07-12 21:12 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: all files reviewed, 20 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/support/commands.ts` line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6oFJxD3DOyjA_r9Yu0:-N6oFJxD3DOyjA_r9Yu1:bs32kop) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/support/commands.ts#L10)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     const intercepts = Cypress.config("intercepts");
> ```

We should talk about the use of `Cypress.config` here..


<!-- Sent from Reviewable.io -->

2022-07-16 07:21 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 4 of 19 files reviewed, 19 unresolved discussions (waiting on @hettlage)

___
*[`cypress/integration/authentication.spec.ts` line 33 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nUrN35FvfP18H6j67:-N74piSR2nfHdYg5fQcO:b-ivxi73) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/authentication.spec.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't you just use a "unique" string?

My concern is that effectively you make the test more complicated than necessary.

(The same comment applies to the other test functions and files, of course.)
</blockquote></details>

As per our discussion, I have changed a couple of things to address this.
___
*[`cypress/integration/forgot-password.spec.ts` line 76 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nVo1-E6WS_yTIMDdf:-N74ps2gA10n4M-yv9cJ:b-zh1chl) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/forgot-password.spec.ts#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are these comments necessary before the it() ?
</blockquote></details>

No, some I forgot to remove them.
___
*[`cypress/integration/login.spec.ts` line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nW9t863jsIG4Mo0DF:-N74pvx0AIx0hOvc90Rr:b-irwpgu) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/login.spec.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't that join with a backslash on Windows?
</blockquote></details>

It probably would, I have changed this as per our discussion.
___
*[`cypress/integration/navigation-bar.spec.ts` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nWk4A3uvqIK_S4XrY:-N74q6Ox63mHX8XYsknk:b-irwpgu) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/navigation-bar.spec.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't that join with a backslash on Windows?
</blockquote></details>

It probably would, I have changed this as per our discussion.
___
*[`cypress/integration/navigation-bar.spec.ts` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nXMOk4YmGldjEDvkT:-N74q8OiE1NGDVWSmHjf:b-22urai) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/navigation-bar.spec.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm a bit concerned (here and everywhere else) that you record an authentication token.
</blockquote></details>

This is now addressed by storing non-real authentication token.
___
*[`cypress/integration/home/home-user.spec.ts` line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nY7Yu6v9fc2ICUCym:-N74qIPqBuJqWwQEO2n8:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no "only".
</blockquote></details>

Done.
___
*[`cypress/integration/home/home-user.spec.ts` line 383 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYdaa88TgU-eU_bpR:-N74qM_tCchOpUQUyYnl:bgxwzuv) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L383)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this really for the Principal Contact only?
</blockquote></details>

This was necessary because some tests had same test names "should show my proposals" and as such their responses was always overwritten.
___
*[`cypress/integration/home/home-user.spec.ts` line 389 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYmOR8-oi5ovmkiAR:-N74qhcy3JcbykfQC1Kh:b2nhky0) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L389)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are these comments necessary?
</blockquote></details>

No.
___
*[`cypress/integration/home/home-user.spec.ts` line 418 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYrGW2t7eHV3LpyRt:-N74qlcj0lBj-SuJpFr3:b-4e6twd) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L418)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this really for the astronomer? If you don't like "my", maybe use "user's"?
</blockquote></details>

See my comment above for the similar test case of principal contacts.
___
*[`cypress/integration/proposal/block-summaries.spec.ts` line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nZFjH4jUadLn7yNww:-N74r-Zv5NOHDcjfiwhP:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/proposal/block-summaries.spec.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hardcoding this URL seems incorrect. (The same applies everywhere else where this might be done.)
</blockquote></details>

Done.
___
*[`cypress/plugins/index.ts` line 91 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nloT699SwipJa6cjo:-N6qlvlrAMKSKeXQd_8s:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/plugins/index.ts#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Read file with JSON content and return its content as an object.

(And maybe the name should be something like readJsonFile?)
</blockquote></details>

Done.
___
*[`cypress/plugins/index.ts` line 105 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6ndOHK9cWIAYJ1N8Uz:-N74r0pq55LwzjhsL_04:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/plugins/index.ts#L105)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Don't you have to use the `recursive` option?
</blockquote></details>

Done.
___
*[`cypress/support/commands.ts` line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nfGgv07sihxca02fA:-N6qmiPx3In9-2hHwgaW:b-xrwrks) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/support/commands.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Does this really store the value?
</blockquote></details>

Yes, it does store the response, as long as it is not already stored in the intercepts dictionary.
Now I have changed this procedure to store this dictionary as an environment variable as per our discussion.
___
*[`cypress/support/index.ts` line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nepZs4bQXYOTYKMYz:-N74rGEoCt2cJK8bGsZE:b32n8ta) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/support/index.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced this should be done... (possibly applies everywhere else as well).
</blockquote></details>

Removed it.
___
*[`cypress/support/index.ts` line 55 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6neiGB3OCWHWM5Yh9U:-N74rISA5GAuI4GXTIfi:b-kj123d) ([raw file](https://gith [...]

2022-07-26 19:29 UTC, hettlage requested changes
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: all files reviewed, 43 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/integration/authentication.spec.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5Cj88RYBpvn0EyX8:-N7u5Cj88RYBpvn0EyX9:b-t349a5) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L14)):*
> ```XML
> describe("Authentication", () => {
>   beforeEach(() => {
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
> ```

The better solution might be to make TypeScripyt aware of the autoRecord command.

See https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands
___
*[`cypress/integration/authentication.spec.ts` line 16 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u26DcEQZQIU_MT7LJ:-N7u26DcEQZQIU_MT7LK:b4f2leg) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L16)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(apiUrl + "/token").as("token");
> ```

Aren't you saving a token here?
___
*[`cypress/integration/authentication.spec.ts` line 22 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u29a0AJ_IvL8jZaML:-N7u29a0AJ_IvL8jZaMM:bldvzsm) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L22)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(apiUrl + "/proposals/**").as("proposals");
> ```

Do you need this in every test?
___
*[`cypress/integration/authentication.spec.ts` line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u2DK77QxFQU7qXUc1:-N7u2DK8BJ4KxbgN-sHY:bldvzsm) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L25)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(apiUrl + "/blocks/**").as("blocks");
> ```

Do you need this in every test?
___
*[`cypress/integration/forgot-password.spec.ts` line 76 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nVo1-E6WS_yTIMDdf:-N7vy52E54C93QALLs7_:bz4g5jw) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/forgot-password.spec.ts#L76)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

No, some I forgot to remove them.
</blockquote></details>

Thera still seem to be there?
___
*[`cypress/integration/forgot-password.spec.ts` line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u3GXa4iLykLmLoJ_u:-N7u3GXa4iLykLmLoJ_v:bldvzsm) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/forgot-password.spec.ts#L19)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(apiUrl + "/users/**").as("users");
> ```

Do you need this in every test?
___
*[`cypress/integration/navigation-bar.spec.ts` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nXMOk4YmGldjEDvkT:-N7vyBt_7IUP9S-FqNUU:bj94qwi) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/navigation-bar.spec.ts#L32)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

This is now addressed by storing non-real authentication token.
</blockquote></details>

But the way it is one might still need discussion. :(
___
*[`cypress/integration/navigation-bar.spec.ts` line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5az5-ph1fRV6qM21:-N7u5az5-ph1fRV6qM22:b4f2leg) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L27)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(apiUrl + "/token").as("token");
> ```

Aren't you saving a token here?
___
*[`cypress/integration/navigation-bar.spec.ts` line 33 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5jEx4KdI_ElgPkFd:-N7u5jEx4KdI_ElgPkFe:bldvzsm) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L33)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(apiUrl + "/proposals/**").as("proposals");
> ```

Do you need this in every test?
___
*[`cypress/integration/navigation-bar.spec.ts` line 146 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u6AhrA3z0pYVyJz0A:-N7u6AhrA3z0pYVyJz0B:b36gvhb) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L146)):*
> ```XML
>   beforeEach(() => {
>     // Ensure the inline login form is not hidden because of a small screen size
>     cy.viewport(1500, 2000);
> ```

Is that really a small screen size...? :-/

Also, are you actually testing what the test is claiming to test?
___
*[`cypress/integration/navigation-bar.spec.ts` line 150 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5z3j2sUg5WFio6ym:-N7u5z3j2sUg5WFio6yn:b-ssfy9g) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L150)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(path.join(apiUrl, "token")).as("token");
> ```

Wouldn't that join with a backslash on Windows?
___
*[`cypress/integration/home/home-user.spec.ts` line 389 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYmOR8-oi5ovmkiAR:-N7vyiLu-uwJ4ywyQ4Fs:b-avmvts) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L389)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

No.
</blockquote></details>

It seems they are still there?
___
*[`cypress/integration/home/home-user.spec.ts` line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u7rGP5_N_eivqPi_3:-N7u7rGP5_N_eivqPi_4:b4f2leg) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/home/home-user.spec.ts#L19)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(path.join(apiUrl, "token")).as("token");
> ```

Aren't you saving a token here?
___
*[`cypress/integration/home/home-user.spec.ts` line 382 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uElEbCk7YdJfdXXUb:-N7uElEbCk7YdJfdXXUc:bldvzsm) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/home/home-user.spec.ts#L382)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     cy.autoRecord(path.join(apiUrl, "proposals/**")).as("proposals");
> ```

Do you need this in every test?
___
*[`cypress/integration/home/home-user.spec.ts` line 413 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uEsQc5BVdw1Rxh2kh:-N7uEsQc5BVdw1Rxh2ki:bldvzsm) ([raw file](https://github.com/saltastroops/ [...]

2022-07-29 10:17 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 7 of 20 files reviewed, 43 unresolved discussions (waiting on @hettlage)

___
*[`cypress/integration/authentication.spec.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5Cj88RYBpvn0EyX8:-N7x_Rtp9htxDx2ZdccV:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The better solution might be to make TypeScripyt aware of the autoRecord command.

See https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands
</blockquote></details>

Done.
___
*[`cypress/integration/authentication.spec.ts` line 16 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u26DcEQZQIU_MT7LJ:-N7x_XKD1zxpYaPBY-8E:b3mfnh) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't you saving a token here?
</blockquote></details>

Not really, I am just intercepting the HTTP request here, the storing of the (non-real) token happens in the custom command `cypress/support/commands.ts`.
___
*[`cypress/integration/authentication.spec.ts` line 22 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u29a0AJ_IvL8jZaML:-N7xa5rx7s1lNvVLW7xn:b-m3rogt) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need this in every test?
</blockquote></details>

Yes, especially the tests that do send HTTP requests to the API. If I remove this for a specific test no request will be intercepted and/or stubbed for that test.
___
*[`cypress/integration/authentication.spec.ts` line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u2DK77QxFQU7qXUc1:-N7xarvm0IYubE4nf_R4:b-m3rogt) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/authentication.spec.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need this in every test?
</blockquote></details>

Yes, especially the tests that do send HTTP requests to the API. If I remove this for a specific test no request will be intercepted and/or stubbed for that test.
___
*[`cypress/integration/forgot-password.spec.ts` line 76 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nVo1-E6WS_yTIMDdf:-N7xb3HY2fFB00XmIRCr:b-q0t6pn) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/forgot-password.spec.ts#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thera still seem to be there?
</blockquote></details>

Should be removed now. Thanks!
___
*[`cypress/integration/forgot-password.spec.ts` line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u3GXa4iLykLmLoJ_u:-N7xatZs-Uxkem1eC1uB:b-m3rogt) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/forgot-password.spec.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need this in every test?
</blockquote></details>

Yes, especially the tests that do send HTTP requests to the API. If I remove this for a specific test no request will be intercepted and/or stubbed for that test.
___
*[`cypress/integration/navigation-bar.spec.ts` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nXMOk4YmGldjEDvkT:-N88QALL2WSp-6sNTw3G:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/navigation-bar.spec.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But the way it is one might still need discussion. :(
</blockquote></details>

Done.
___
*[`cypress/integration/navigation-bar.spec.ts` line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5az5-ph1fRV6qM21:-N7xdXmkBeIw2br6IML2:b3mfnh) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't you saving a token here?
</blockquote></details>

Not really, I am just intercepting the HTTP request here, the storing of the (non-real) token happens in the custom command `cypress/support/commands.ts`.
___
*[`cypress/integration/navigation-bar.spec.ts` line 33 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5jEx4KdI_ElgPkFd:-N7xbA9d2oTub8RzIfNx:b-m3rogt) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you need this in every test?
</blockquote></details>

Yes, especially the tests that do send HTTP requests to the API. If I remove this for a specific test no request will be intercepted and/or stubbed for that test.
___
*[`cypress/integration/navigation-bar.spec.ts` line 146 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u6AhrA3z0pYVyJz0A:-N7xbQTB0TD8BYbQh6be:b-170h5q) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L146)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is that really a small screen size...? :-/

Also, are you actually testing what the test is claiming to test?
</blockquote></details>

As per our discussion this comment is invalid.
___
*[`cypress/integration/navigation-bar.spec.ts` line 150 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5z3j2sUg5WFio6ym:-N7xdLMK6AvIAYex6b9Y:b-ybw447) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L150)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't that join with a backslash on Windows?
</blockquote></details>

Fixed now.
___
*[`cypress/integration/home/home-user.spec.ts` line 389 at r1](https://reviewable.io/reviews/saltastroops/web-manager/130#-N6nYmOR8-oi5ovmkiAR:-N7xdzj7DAmhzSiE0Arn:bjam3s4) ([raw file](https://github.com/saltastroops/web-manager/blob/f43dc0f6f357f1c705681ac00eacb6f936fa595e/cypress/integration/home/home-user.spec.ts#L389)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems they are still there?
</blockquote></details>

It should be fixed now.
___
*[`cypress/integration/home/home-user.spec.ts` line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u7rGP5_N_eivqPi_3:-N7xdedO35WvT-9k8VXe:b3mfnh) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/home/home-user.spec.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't you saving a token here?
</blockquote></details>

Not really, I am just intercepting the HTTP request here, the storing of the (non-real) token happens in the custom command `cypress/support/commands.ts`.
___
*[`cypress/integration/home/home-user.spec.ts` line 382 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uElEbCk7YdJfdXXUb:-N7xpHtb9hs2zNG7qHd_:b-m3rogt) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/home/home-user.spec.ts#L3 [...]

2022-07-30 19:33 UTC, hettlage requested changes
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: all files reviewed, 20 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/integration/authentication.spec.ts` line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N89ZysZ-IImXAwSnsW6:-N89ZysZ-IImXAwSnsW7:b-1zgpb4) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/integration/authentication.spec.ts#L8)):*
> ```XML
> } from "../support/pages/proposal-page";
> 
> const apiUrl = Cypress.env("apiUrl");
> ```

This should be handled by a utility function which raises a meaningful error if the environment variable isn't set.
___
*[`cypress/integration/navigation-bar.spec.ts` line 150 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5z3j2sUg5WFio6ym:-N88TYt82JNmW_YUz56y:b-4g9f9g) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L150)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Fixed now.
</blockquote></details>

But `path` is still being used...?
___
*[`cypress/integration/home/home-user.spec.ts` line 396 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N88Tqe9Ai86pDhPPGAk:-N88Tqe9Ai86pDhPPGAl:b-55j6t0) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/integration/home/home-user.spec.ts#L396)):*
> ```XML
>   beforeEach(() => {
>     USERNAME = Cypress.env("pcUsername");
>     cy.autoRecord(path.join(apiUrl, "token")).as("token");
> ```

`platt` is still being used.
___
*[`cypress/integration/proposal/block-summaries.spec.ts` line 157 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uKyzF2-CNl6d-jkl9:-N88UxEZED7HTDasA6oV:b-se0kwe) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/proposal/block-summaries.spec.ts#L157)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That is true in principle but given the fact that it is challenging to wait for multiple intercepted requests that have the same alias. For this specific test, two block requests are made, the first is made when the first block on the list is requested when the proposal page loads. The second request is made after clicking on the block name link. As a result, it makes perfect sense to wait after clicking the block so that we wait after the second block request is made.
</blockquote></details>

But... strictly speaking, there is no guarantee that the first block request is finished by the time when you  click on the block name link. so I don't think there is a guarantee that you are waiting for the second block request. At least theoretically, the test might be flaky.

It seems you can wait before and after clicking on the link, though.
___
*[`cypress/integration/proposal/observation-comments.spec.ts` line 48 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uM_L2-E1SCXpNSy0X:-N89ic0J1RHfS2lqmlQy:bjzr4py) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/proposal/observation-comments.spec.ts#L48)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

When I do that, I risk not intercepting/stubbing other requests. For instance, when multiple requests of the same alias are made to the API, not all of them will be intercepted and/or stubbed (see my comment above).
</blockquote></details>

I';nm not sure I understand this... Let's chat on Monday.
___
*[`cypress/support/commands.ts` line 25 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8ASF4bBnP50I_gg8Xl:-N8ASF4bBnP50I_gg8Xm:b-gmetgs) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L25)):*
> ```XML
> }
> 
> function getInterceptsCounts(url): number {
> ```

I don't think this function is necessary; `push` and `shift` should work fine.

Maybe we can chat about this on Monday?
___
*[`cypress/support/commands.ts` line 62 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AUt0R9FciaclXkZaJ:-N8AUt0R9FciaclXkZaK:botxybo) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L62)):*
> ```XML
>     const key = `${request.method}-${request.url}`;
> 
>     const intercepts = getAllResponses();
> ```

I'd move all the logic for getting and storing responses into utility functions.

Maybe we can chat about this on Monday?
___
*[`cypress/support/commands.ts` line 63 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AUGt826PvEhEj3TI0:-N8AUGt826PvEhEj3TI1:b-akixtn) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L63)):*
> ```XML
> 
>     const intercepts = getAllResponses();
>     // delete undefined entries from the dictionary
> ```

Why do you do this?
___
*[`cypress/support/commands.ts` line 65 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AURXA3G-tJv1YGGRT:-N8AURXBBk5iT9XNADvW:beeoobl) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L65)):*
> ```XML
>     // delete undefined entries from the dictionary
>     Object.keys(intercepts).forEach(
>       (key) => intercepts[key] == undefined && delete intercepts[key],
> ```

The variable name `key` is shadowing the other `key` variable, which might be confusing.
___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N8AW7Vf41DchNY2IqKM:b-5hc91c) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

You're right. However, I found out that Cypress automatically converts the `Cypress.env` values to the dictionary, even if they are passed as arguments on the command-line interface. Anyway, it no longer necessary, since i am using a helper function now.
</blockquote></details>

I'm still not convinced.
___
*[`cypress/support/index.ts` line 15 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8FYo4i9dRBlrtLFL9a:-N8FYo4i9dRBlrtLFL9b:b-3nuck) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L15)):*
> ```XML
> const interceptsConfig = Cypress.env("interceptsConfig") || {};
> const mockIntercepts = interceptsConfig.mockIntercepts || false;
> const forceRecord = interceptsConfig.forceRecord || false;
> ```

I have the feeling that we have different opinions on what `forceRecord` should actually do.
___
*[`cypress/support/index.ts` line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AVYqw8D_UK6QNcF_b:-N8AVYqw8D_UK6QNcF_c:b1kaey5) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L6)):*
> ```XML
> import { getAllResponses, parseMockPath, recordResponses } from "./utils";
> 
> // load type definitions that come with Cypress module
> ```

Maybe better: type definitions for custom commands
___
*[`cypress/support/index.ts` line 13 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AVpjzBLrNAJ4vq774:-N8AVpjzBLrNAJ4vq775:bxskyx4) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L13)):*
> ```XML
>     interface Chainable {
>       /**
>        *  [...]

2022-08-08 12:51 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 7 of 20 files reviewed, 20 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`cypress/integration/authentication.spec.ts` line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N89ZysZ-IImXAwSnsW6:-N8S-Xzp--piMoQSeR-o:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/integration/authentication.spec.ts#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be handled by a utility function which raises a meaningful error if the environment variable isn't set.
</blockquote></details>

Done.
___
*[`cypress/integration/navigation-bar.spec.ts` line 150 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7u5z3j2sUg5WFio6ym:-N8S-hdy2E0S10FmK2tl:byrh8e) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/navigation-bar.spec.ts#L150)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But `path` is still being used...?
</blockquote></details>

That's a bit weird, I did fix it and it appears to be the case on my side.
___
*[`cypress/integration/home/home-user.spec.ts` line 396 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N88Tqe9Ai86pDhPPGAk:-N8S01XPA11E81EJRs9V:byrh8e) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/integration/home/home-user.spec.ts#L396)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`platt` is still being used.
</blockquote></details>

That's a bit weird, I did fix it and it appears to be the case on my side.
___
*[`cypress/integration/proposal/block-summaries.spec.ts` line 157 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uKyzF2-CNl6d-jkl9:-N8xU0EX4lAWL9gSRGlw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/proposal/block-summaries.spec.ts#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But... strictly speaking, there is no guarantee that the first block request is finished by the time when you  click on the block name link. so I don't think there is a guarantee that you are waiting for the second block request. At least theoretically, the test might be flaky.

It seems you can wait before and after clicking on the link, though.
</blockquote></details>

Done.
___
*[`cypress/integration/proposal/observation-comments.spec.ts` line 48 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uM_L2-E1SCXpNSy0X:-N8xU1aH4fAPCmBRZdXU:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/integration/proposal/observation-comments.spec.ts#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I';nm not sure I understand this... Let's chat on Monday.
</blockquote></details>

Done.
___
*[`cypress/support/commands.ts` line 25 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8ASF4bBnP50I_gg8Xl:-N8xL7UIDfFTnxGaD-Cy:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this function is necessary; `push` and `shift` should work fine.

Maybe we can chat about this on Monday?
</blockquote></details>

Done.
___
*[`cypress/support/commands.ts` line 62 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AUt0R9FciaclXkZaJ:-N8xL8ph4xUxRHLmeVFn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd move all the logic for getting and storing responses into utility functions.

Maybe we can chat about this on Monday?
</blockquote></details>

Done.
___
*[`cypress/support/commands.ts` line 63 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AUGt826PvEhEj3TI0:-N8S3SDj9g9xyIKzBlNZ:bqes93d) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you do this?
</blockquote></details>

For some reason, there's always an undefined key-value pair in the dictionary. However, this is no longer the issue since I have removed this code.
___
*[`cypress/support/commands.ts` line 65 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AURXA3G-tJv1YGGRT:-N8S3Qi048wqLloXo0P5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/commands.ts#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The variable name `key` is shadowing the other `key` variable, which might be confusing.
</blockquote></details>

Done.
___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N8S3g8G7sXFlOdkMcBc:bh427xf) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm still not convinced.
</blockquote></details>

I know and you have already mentioned that it is because the documentation states otherwise.
___
*[`cypress/support/index.ts` line 15 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8FYo4i9dRBlrtLFL9a:-N8xLWiPC9E6JMuszHsN:bg538p8) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I have the feeling that we have different opinions on what `forceRecord` should actually do.
</blockquote></details>

As per our discussion, `forceRecord` functionality is now replaced with `mockIntercepts`.
___
*[`cypress/support/index.ts` line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AVYqw8D_UK6QNcF_b:-N8S0ZUTCrYUMKVvflhS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: type definitions for custom commands
</blockquote></details>

Done.
___
*[`cypress/support/index.ts` line 13 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AVpjzBLrNAJ4vq774:-N8S0tVX9v7jkoV9F7CD:bqeu8ud) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This comment definitely is wrong... :-)
</blockquote></details>

I have fixed it now.
___
*[`cypress/support/index.ts` line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AWJcO2mh3FIX4_mQj:-N8xNATH4CDiSq94O7Gd:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be worth adding how the mock file directory is set.
</blockquote></details>

Done.
___
*[`cypress/support/index.ts` line 43 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AWdtb1xBQlUQXhgMo:-N8xTfvk4mXq0obFaveZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts [...]

2022-08-08 15:24 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 7 of 20 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[`cypress/support/utils.ts` line 157 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uafM0B44W4EnLyQ6N:-N8S2yRX1_x2luv4WAqP:b-326i87) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/utils.ts#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, but I think this still needs discussion. I may be wrong, but I have the suspicion this function won't work if you have different directory depth for your test files.
</blockquote></details>

It is working as expected I think and we did verify this during our meeting. I have also added a way to handle path splitting by a separator that is platform-specific


<!-- Sent from Reviewable.io -->

2022-08-10 12:42 UTC, hettlage requested changes
> Reviewed 11 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 18 of 20 files reviewed, 31 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`cypress/integration/authentication.spec.ts` line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N967o1t4U3DpJSD6nui:-N967o1t4U3DpJSD6nuj:b-ruxj1u) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/authentication.spec.ts#L15)):*
> ```XML
> describe("Authentication", () => {
>   beforeEach(() => {
>     cy.recordAndMockApi(apiUrl + "/token").as("token");
> ```

Maybe better something like "recordOrMock"? Or "recordHttp"?
___
*[`cypress/integration/navigation-bar.spec.ts` line 71 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96E97c2Y85BpDN10cc:-N96E97d2LQfpG9UmyDz:b-yd4uee) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L71)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     { tags: "@skip" },
> ```

Why the skip tag?
___
*[`cypress/integration/navigation-bar.spec.ts` line 101 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96ECuY3Xo1viIhdhRB:-N96ECuY3Xo1viIhdhRC:b-yd4uee) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L101)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     { tags: "@skip" },
> ```

Why the skip tag?
___
*[`cypress/integration/navigation-bar.spec.ts` line 121 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96EafwANWE_SmWNcrl:-N96EafxEVRVU1gSNUX-:b-yd4uee) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L121)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     { tags: "@skip" },
> ```

Why the skip tag?
___
*[`cypress/integration/navigation-bar.spec.ts` line 144 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96FLd15dOW1iFm6kuP:-N96FLd15dOW1iFm6kuQ:b-1ace29) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L144)):*
> ```XML
>     cy.viewport(1500, 2000);
> 
>     cy.recordAndMockApi(path.join(apiUrl, "token")).as("token");
> ```

There still is a `path.join` here...
___
*[`cypress/integration/home/home-user.spec.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96Ffzz9r0enX_PnoCI:-N96Ffzz9r0enX_PnoCJ:b-msakm6) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/home/home-user.spec.ts#L1)):*
> ```XML
> import * as path from "path";
> ```

`path` is still being used...
___
*[`cypress/integration/login/change-password.spec.ts` line 97 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96FrsJEEFyMDL_TDx8:-N96FrsJEEFyMDL_TDx9:b-yd4uee) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/login/change-password.spec.ts#L97)):*
> ```XML
>     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
>     // @ts-ignore
>     { tags: "@skip" },
> ```

Why the skip tag?
___
*[`cypress/plugins/index.ts` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96HLhfELA3aUyRhcb9:-N96HLhfELA3aUyRhcbA:b5gx3jj) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/plugins/index.ts#L18)):*
> ```XML
> const fs = require("fs");
> 
> // const stubConfig = Cypress.env("stubApi") || {};
> ```

Are these commented out lines still needed?
___
*[`cypress/support/commands.ts` line 31 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96lQ1H9gXyfLoNbi0X:-N96lQ1H9gXyfLoNbi0Y:bvn31no) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/commands.ts#L31)):*
> ```XML
>     if (mockIntercepts) {
>       try {
>         const response = { ...JSON.parse(getResponse(key)) };
> ```

Isn't `{ ...JSON.parse(getResponse(key)) }` the same as just `.JSON.parse(getResponse(key))`?
___
*[`cypress/support/utils.ts` line 136 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96jkHTBV2dphtuP_z2:-N96jkHTBV2dphtuP_z3:b-g1u7qg) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L136)):*
> ```XML
>  * Parses mock directory path.
>  */
> export function parseMockPath(directoryPath: PathLike): string[] {
> ```

"parse" might be inaccurate -- you are actually _generating_ a path, really.
___
*[`cypress/support/utils.ts` line 161 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96M7Es7J8J3r7yEVT0:-N96M7Es7J8J3r7yEVT1:bq2lycl) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L161)):*
> ```XML
>  */
> export function saveResponse(
>   key: string = null,
> ```

Can the key be omitted? Can the response be omitted? In other words, should there really be a default null value?
___
*[`cypress/support/utils.ts` line 162 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96MJ7q1xEgMvsdl8gi:-N96MJ7q1xEgMvsdl8gj:b8llxrj) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L162)):*
> ```XML
> export function saveResponse(
>   key: string = null,
>   responses: string[] = null,
> ```

Why is this an array rather than a string?
___
*[`cypress/support/utils.ts` line 171 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96j17d1uDknC11dgGM:-N96j17d1uDknC11dgGN:b1yto2y) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L171)):*
> ```XML
>     }
>   } else {
>     recordedResponses = {};
> ```

This looks wrong. Why would you delete _all_ recoded responses just because a key is `null`? 
___
*[`cypress/support/utils.ts` line 176 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96KvGl1_fMG0W21kjK:-N96KvGl1_fMG0W21kjL:b7xvk65) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L176)):*
> ```XML
> 
> /**
>  * Get all recorded/stored responses.
> ```

You don't get all responses; you only get the next. :-)
___
*[`cypress/support/utils.ts` line 179 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96L3r_4sYmsHihHXq1:-N96L3r_4sYmsHihHXq2:b91e711) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L179)):*
> ```XML
>  */
> export function getResponse(key: string): string {
>   return recordedResponses[key].length > 1
> ```

This should be just:

```
return recordedResponses[key].shift();
```

Yes, I know this fails, but I'd think that means there is an issue somewhere.
___
*[`cypress/support/utils.ts` line 190 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96LIq4AGI-vVbL4t7i:-N96LIq4AGI-vVbL4t7j:b-fl82d0) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L190)):*
> ```XML
>   const apiUrl = Cypress.env("apiUrl") || null;
>   if (!apiUrl) {
>     throw new Error("API URL not found.");
> ```

You should add how the URL is set.
___
*[`cypress/integration/login/login.spec.ts` line 77 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96GjfwE9y2zJWt7rh8:-N96G [...]

2022-08-10 12:47 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 18 of 20 files reviewed, 20 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`cypress/integration/home/home-user.spec.ts` line 396 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N88Tqe9Ai86pDhPPGAk:-N96mgFzDxp6H_Qlwb4n:b-o9lkuw) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/integration/home/home-user.spec.ts#L396)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's a bit weird, I did fix it and it appears to be the case on my side.
</blockquote></details>

It's still there... :(
___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N969zkP-z5U7NSnhwAC:bmvvzl2) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I know and you have already mentioned that it is because the documentation states otherwise.
</blockquote></details>

And it is arguably what you'd expect for environment variables.
___
*[`cypress/support/index.ts` line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AWJcO2mh3FIX4_mQj:-N96m7ru7cF02dNr5KAz:bn4q3u5) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L34)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. But I think the example is a bit misleading, as it fails to note the `recordAndMockApi` key.


<!-- Sent from Reviewable.io -->

2022-08-15 14:05 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 5 of 20 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[`cypress/integration/authentication.spec.ts` line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N967o1t4U3DpJSD6nui:-N9WivCn7bcVwahjIBo5:bbca7zl) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/authentication.spec.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better something like "recordOrMock"? Or "recordHttp"?
</blockquote></details>

recordHttp it is.
___
*[`cypress/integration/navigation-bar.spec.ts` line 71 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96E97c2Y85BpDN10cc:-N973fv1AWn5ttb5Ch1i:b-ev4w75) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the skip tag?
</blockquote></details>

Somehow I thought the request was not sent to the backend, my mistake. I have fixed this, the test is no longer skipped.
___
*[`cypress/integration/navigation-bar.spec.ts` line 101 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96ECuY3Xo1viIhdhRB:-N96sffLDfjFY31qb7yl:b-mvjntq) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L101)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the skip tag?
</blockquote></details>

The token request is intercepted indefinitely, as such, the request is never sent to the backend and also the response is never returned. Thus, the plugin will also wait indefinitely if the test is not skipped.
___
*[`cypress/integration/navigation-bar.spec.ts` line 121 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96EafwANWE_SmWNcrl:-N96tek549ptuM52ILg_:b-mvjntq) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L121)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the skip tag?
</blockquote></details>

The token request is intercepted indefinitely, as such, the request is never sent to the backend and also the response is never returned. Thus, the plugin will also wait indefinitely if the test is not skipped.
___
*[`cypress/integration/navigation-bar.spec.ts` line 144 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96FLd15dOW1iFm6kuP:-N96trGZ9ENG1NiYx6kv:b8jr6a6) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/navigation-bar.spec.ts#L144)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There still is a `path.join` here...
</blockquote></details>

Thanks, I have removed it now.
___
*[`cypress/integration/home/home-user.spec.ts` line 396 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N88Tqe9Ai86pDhPPGAk:-N96uT9Z9h3e2xRJkuB9:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/integration/home/home-user.spec.ts#L396)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It's still there... :(
</blockquote></details>

Done.
___
*[`cypress/integration/home/home-user.spec.ts` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96Ffzz9r0enX_PnoCI:-N96u7Zo7FKVXny9XgEg:b8jr6a6) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/home/home-user.spec.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`path` is still being used...
</blockquote></details>

Thanks, I have removed it now.
___
*[`cypress/integration/login/change-password.spec.ts` line 97 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96FrsJEEFyMDL_TDx8:-N96uZne5KGCpNnl54Ed:b-m2tffc) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/integration/login/change-password.spec.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the skip tag?
</blockquote></details>

The user request is intercepted indefinitely, as such, the request is never sent to the backend and also the response is never returned. Thus, the plugin will also wait indefinitely if the test is not skipped.
___
*[`cypress/plugins/index.ts` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96HLhfELA3aUyRhcb9:-N96uvIP5gb5D8QBRKdB:b-zgbpls) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/plugins/index.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are these commented out lines still needed?
</blockquote></details>

Nope, I have removed them.
___
*[`cypress/support/commands.ts` line 31 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96lQ1H9gXyfLoNbi0X:-N974utm7_SUr62q0oQZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/commands.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't `{ ...JSON.parse(getResponse(key)) }` the same as just `.JSON.parse(getResponse(key))`?
</blockquote></details>

Done.
___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N96yK9cEdW04atVcqCQ:b-actrz6) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And it is arguably what you'd expect for environment variables.
</blockquote></details>

I guess I was right, maybe the documentation needs updating. Cypress actually gives an error when I try to parse to JSON: `> Unexpected token o in JSON at position 1`
___
*[`cypress/support/index.ts` line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager/130#-N8AWJcO2mh3FIX4_mQj:-N96yYV650-WTICdY08h:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ef438701766a920af91c41c5eb46c0150d59fa7/cypress/support/index.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks. But I think the example is a bit misleading, as it fails to note the `recordAndMockApi` key.
</blockquote></details>

Done.
___
*[`cypress/support/utils.ts` line 136 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96jkHTBV2dphtuP_z2:-N96yic9DDw4VyMt0SdA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L136)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"parse" might be inaccurate -- you are actually _generating_ a path, really.
</blockquote></details>

Done.
___
*[`cypress/support/utils.ts` line 161 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96M7Es7J8J3r7yEVT0:-N97B2pMAOr6tRnQSvER:btimne0) ([raw file](https://github.com/saltastroops/web-manager/blob/83ec5869249474cdaad5560ace35000516be6ece/cypress/support/utils.ts#L161)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can the key be omitted? Can the response be omitted? In other words, should there really be a default null value?
</blockquote></details>

I was allowing null values so that I can delete all records when they are null. I have changed this accordingly.
___
*[`cypress/support/utils.ts` line 162 at r4](https://reviewable.io/reviews/saltastroops/web-manager/130#-N96MJ7q [...]

2022-08-16 13:03 UTC, hettlage requested changes
> Reviewed 14 of 15 files at r5, 4 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 21 of 22 files reviewed, 11 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`tsconfig.json` line 28 at r6](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9ahWoOEetqVhdKGRFr:-N9ahWoPAlimq6WAK9oe:bgs5vpq) ([raw file](https://github.com/saltastroops/web-manager/blob/01e5c6fdb36c7bcd7b5be8af504f2d22080f51e1/tsconfig.json#L28)):*
> ```jsonc
>     "strictTemplates": true
>   },
>   "exclude": ["cypress"]
> ```

Why do you exclude this folder?
___
*[`cypress/integration/authentication.spec.ts` line 31 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9_WBPqDxL8O4DFJaS-:-N9_WBPqDxL8O4DFJaS0:bnvmtgy) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/integration/authentication.spec.ts#L31)):*
> ```XML
> 
>       // Then user details are stored
>       userAreDetailsStored();
> ```

Maybe better `userDetailsAreStored` ?
___
*[`cypress/integration/authentication.spec.ts` line 43 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9_W7CeCuTXpPz0tOfX:-N9_W7CeCuTXpPz0tOfY:btl5u15) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/integration/authentication.spec.ts#L43)):*
> ```XML
>       // And try to add an observation comment
>       ObservationComments.addComment("This is a test comment.");
>       // cy.wait("@proposals");
> ```

Line should be removed
___
*[`cypress/integration/forgot-password.spec.ts` line 68 at r6](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9ahg9M0TAEbH_y7Lct:-N9ahg9M0TAEbH_y7Lcu:b-72nrgb) ([raw file](https://github.com/saltastroops/web-manager/blob/01e5c6fdb36c7bcd7b5be8af504f2d22080f51e1/cypress/integration/forgot-password.spec.ts#L68)):*
> ```XML
>   });
> 
>   it.only("should send an email with the correct password reset link", () => {
> ```

"only" should be removed.
___
*[`cypress/integration/proposal/block-summaries.spec.ts` line 27 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9_ZM-I2jUk-tSkZhPG:-N9_ZM-I2jUk-tSkZhPH:b-17iol6) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/integration/proposal/block-summaries.spec.ts#L27)):*
> ```XML
>     });
>     // Then user details are stored
>     userAreDetailsStored();
> ```

I'm not entirely sure why you've added this to tests?
___
*[`cypress/support/commands.ts` line 47 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9__UNQ5qjQT7SmIQCU:-N9__UNQ5qjQT7SmIQCV:btl5u15) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/support/commands.ts#L47)):*
> ```XML
>     } else {
>       request.continue((response) => {
>         // response.delay = 10;
> ```

Line should be removed
___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N9aiKFo4oKG7bstgvb_:bw69t0c) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I guess I was right, maybe the documentation needs updating. Cypress actually gives an error when I try to parse to JSON: `> Unexpected token o in JSON at position 1`
</blockquote></details>

I'm not sure I entirely understand this comment... :(
___
*[`cypress/support/utils.ts` line 210 at r6](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9ajsSA0QMw9XLUjTy9:-N9ajsSA0QMw9XLUjTyA:b-vz1mm8) ([raw file](https://github.com/saltastroops/web-manager/blob/01e5c6fdb36c7bcd7b5be8af504f2d22080f51e1/cypress/support/utils.ts#L210)):*
> ```XML
> 
> /**
>  * Disable and/or clear browser's cache.
> ```

clear browser's > clear the browser


<!-- Sent from Reviewable.io -->

2022-08-16 13:54 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: 12 of 22 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`tsconfig.json` line 28 at r6](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9ahWoOEetqVhdKGRFr:-N9asiPCEzhv1h3tXhii:b-lxnb84) ([raw file](https://github.com/saltastroops/web-manager/blob/01e5c6fdb36c7bcd7b5be8af504f2d22080f51e1/tsconfig.json#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you exclude this folder?
</blockquote></details>

 It seems cypress and jest both declare types for expect. In this case, the cypress declaration seems to be the one that is picked up. I also tried the suggested solution in the link you shared by excluding `./cypress.config.ts` file in the `tsconfig.json` and it didn't work, probably because we are not using the latest Cypress version, v10?

The solution that worked was to exclude both `cypress`and `./cypress.config.ts` file from `./tsconfig.json`, this makes sense because this type is included in the `cypress/tsconfig.json` file.
___
*[`cypress/integration/authentication.spec.ts` line 31 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9_WBPqDxL8O4DFJaS-:-N9anVbbDcm9EYydKbNG:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/integration/authentication.spec.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better `userDetailsAreStored` ?
</blockquote></details>

Done.
___
*[`cypress/integration/authentication.spec.ts` line 43 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9_W7CeCuTXpPz0tOfX:-N9ao7W05JD8d8iRnN4o:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/integration/authentication.spec.ts#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Line should be removed
</blockquote></details>

Done.
___
*[`cypress/integration/forgot-password.spec.ts` line 68 at r6](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9ahg9M0TAEbH_y7Lct:-N9aoGj-Cwfl_uDgxC_W:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/01e5c6fdb36c7bcd7b5be8af504f2d22080f51e1/cypress/integration/forgot-password.spec.ts#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"only" should be removed.
</blockquote></details>

Done.
___
*[`cypress/integration/proposal/block-summaries.spec.ts` line 27 at r5](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9_ZM-I2jUk-tSkZhPG:-N9aoK8--vBiyyXanYCT:b-dk3aih) ([raw file](https://github.com/saltastroops/web-manager/blob/f90fad08e4498518ef8bb4386b9607d1c254b1a9/cypress/integration/proposal/block-summaries.spec.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not entirely sure why you've added this to tests?
</blockquote></details>

The problem is that the token request somehow gets cancelled without this assertion.
___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N9aoXjl04_r_V9futRs:bid31rb) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure I entirely understand this comment... :(
</blockquote></details>

I tried parsing to JSON as per our discussion and the documentation >>> `JSON.parse(Cypress.env("recordHttpConfig") || "{}")`, I get the above error.
___
*[`cypress/support/utils.ts` line 210 at r6](https://reviewable.io/reviews/saltastroops/web-manager/130#-N9ajsSA0QMw9XLUjTy9:-N9aqUI50pKlDGnsB4RJ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/01e5c6fdb36c7bcd7b5be8af504f2d22080f51e1/cypress/support/utils.ts#L210)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

clear browser's > clear the browser
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 15:08 UTC, hettlage approved these changes
> Reviewed 1 of 5 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/130)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`cypress/support/index.ts` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/130#-N7uQsVODbgl2cXW1Pdo:-N9bBFueAXcItURf9BBS:b-kp3sk6) ([raw file](https://github.com/saltastroops/web-manager/blob/d0de295accfaf3f257460ec7198ed5ab53ca07db/cypress/support/index.ts#L14)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I tried parsing to JSON as per our discussion and the documentation >>> `JSON.parse(Cypress.env("recordHttpConfig") || "{}")`, I get the above error.
</blockquote></details>

But my point would be that env variables shouldn't be JSON... But I guess I can use the move to a stand-alone plugin to sneakily sneak in such a change.


<!-- Sent from Reviewable.io -->

2022-08-16 15:09 UTC, merged