register-new-user
saltastroops/web-manager pull request #209
Opened 2023-01-16 05:32 UTC by mofokeng-chaka

Register user page

2023-01-20 16:03 UTC, hettlage requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/209)* status: all files reviewed, 23 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/navigation-bar/navigation-bar.component.html` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEPDt15pCg-gnhG3_0:-NMEPDt15pCg-gnhG3_1:b2zuy4w) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/navigation-bar/navigation-bar.component.html#L8)):*
> ```HTML
>         <a
>           class="navbar-item"
>           routerLink="register-new-user"
> ```

Couldn't the link just be `/register`?
___
*[`src/app/register-user/register-user.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEahvp2C1woi8uV99R:-NMEahvp2C1woi8uV99S:b-7dqmsq) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L1)):*
> ```HTML
> <div class="register-new-user-form register-new-user-page">
> ```

General remarks:

The spacing between input fields, error messages and field labels is not ideal.

The spacing between the dropdown menus and the following field values is not ideal.

The background colours of the input fields and the text area are inconsistent.
___
*[`src/app/register-user/register-user.component.html` line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEQTLK4ZSd9d06TNH9:-NMEQTLK4ZSd9d06TNHA:bqrkgb) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L17)):*
> ```HTML
>       />
>       <div
>         *ngIf="(f.username.dirty || submitted) && f.username.errors"
> ```

Shouldn't `dirty` be `touched`?
___
*[`src/app/register-user/register-user.component.html` line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEPlQC7jrpF1NUM48Q:-NMEPlQC7jrpF1NUM48R:b6r2dpe) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L53)):*
> ```HTML
>             Password is required
>           </div>
>           <div *ngIf="f.password.errors.minlength">
> ```

must be >  must have

Also, shouldn't you hide this error if the "Password is required" error is displayed?
___
*[`src/app/register-user/register-user.component.html` line 155 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMESoP1CajzmFnUdz6d:-NMESoP1CajzmFnUdz6e:bcimk1g) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L155)):*
> ```HTML
>       <select formControlName="partner" (change)="onSelectPartner($event)">
>         <option value="-1">please select partner</option>
>         <option *ngFor="let partner of partners" [value]="Partner[partner]">
> ```

Only active pertness should be shown.
___
*[`src/app/register-user/register-user.component.html` line 185 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMER8MACRwfLBOXrAwI:-NMER8MACRwfLBOXrAwJ:b-cayik5) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L185)):*
> ```HTML
>           (change)="onSelectInstitute($event)"
>         >
>           <option value="-1">please select institute</option>
> ```

Might it make more sense to use the value `null` in this case?
___
*[`src/app/register-user/register-user.component.html` line 353 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMERz-F7zpuh4JrQ_4L:-NMERz-F7zpuh4JrQ_4M:b-oeb0mu) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L353)):*
> ```HTML
>       </div>
>     </div>
>     <br />
> ```

<br> elements should be avoided.
___
*[`src/app/register-user/register-user.component.ts` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEXmx_CFwqIplARidn:-NMEXmx_CFwqIplARido:b-9scjsx) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L1)):*
> ```XML
> import { Component, OnInit } from "@angular/core";
> ```

I think institutions can be handled better:

1. There is no ADD NEW INSTITUTION item in the institutions dropdown list.
2. Instead there is an Add new institution link.
3. If you click on that link a popup with the new institution form opens.
4. When the form is submitted successfully, the popup closes, a reload of institutions is triggered and the new institution is selected.
___
*[`src/app/register-user/register-user.component.ts` line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEWs-fCj9Ysg-CfTOd:-NMEWs-fCj9Ysg-CfTOe:b-vo3vur) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L35)):*
> ```XML
> })
> export class RegisterUserComponent implements OnInit {
>   public Partner = Partner;
> ```

This line looks odd to me.
___
*[`src/app/register-user/register-user.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMENSM1Bib45lsjAkpy:-NMENSM1Bib45lsjAkpz:b4uxq00) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L36)):*
> ```XML
> export class RegisterUserComponent implements OnInit {
>   public Partner = Partner;
>   registerNewUserForm!: UntypedFormGroup;
> ```

Why don't you use a typed form group?
___
*[`src/app/register-user/register-user.component.ts` line 38 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEWSvP7Bq9UkovJqGZ:-NMEWSvP7Bq9UkovJqG_:bd0epku) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L38)):*
> ```XML
>   registerNewUserForm!: UntypedFormGroup;
>   loading = false;
>   submitted = false;
> ```

I don't think the `submitted` variable u=is necessary. There should be a `FormGroup` flag for this.
___
*[`src/app/register-user/register-user.component.ts` line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEXVAzD-szG2eYrBWj:-NMEXVAzD-szG2eYrBWk:b-th5329) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L41)):*
> ```XML
>   error: string | undefined = undefined;
>   institutionsMapping = new Map();
>   partners!: Array<keyof typeof Partner>;
> ```

Wouldn't this just be `Partner[]`?
___
*[`src/app/register-user/register-user.component.ts` line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEY_OwAVEjSg9QyLJf:-NMEY_OwAVEjSg9QyLJg:b-bgc8he) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L43)):*
> ```XML
>   partners!: Array<keyof typeof Partner>;
>   partnerInstitutions!: Institution[];
>   showAddNewInstitutionControls = false;
> ```

See general comment regarding institutions above.
___
*[`src/app/register-user/register-user.component.ts` line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEX8pl3UNGp5pnQj7y:-NMEX8pl3UNGp5pnQj7z:bcbrwpc) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L44)):*
> ```XML
>   partnerInstitutions!: Institution[];
>   showAddNewInstitutionControls = false;
>   showInstitutions = false;
> ```

Do you need this? Can't you check whether `partnerInstitutions `has a  [...]

2023-01-24 08:29 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/209)* status: 7 of 13 files reviewed, 23 unresolved discussions (waiting on @hettlage)

___
*[`src/app/navigation-bar/navigation-bar.component.html` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEPDt15pCg-gnhG3_0:-NMTI8mu5CvxNVEGsuW7:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/navigation-bar/navigation-bar.component.html#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Couldn't the link just be `/register`?
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEahvp2C1woi8uV99R:-NMTTMPQCC4x4wOHiQFg:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

General remarks:

The spacing between input fields, error messages and field labels is not ideal.

The spacing between the dropdown menus and the following field values is not ideal.

The background colours of the input fields and the text area are inconsistent.
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.html` line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEQTLK4ZSd9d06TNH9:-NMWsXho2SHA0k2RI6H9:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't `dirty` be `touched`?
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.html` line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEPlQC7jrpF1NUM48Q:-NMTUXoYBcF7v6kpmeVe:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

must be >  must have

Also, shouldn't you hide this error if the "Password is required" error is displayed?
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.html` line 155 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMESoP1CajzmFnUdz6d:-NMWsa0s6SC63VbOl1tP:bn9cno4) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Only active pertness should be shown.
</blockquote></details>

Which partners are considered active? I also looked at the old WM, which shows the same list of partners as the ones displayed by the above code.
___
*[`src/app/register-user/register-user.component.html` line 185 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMER8MACRwfLBOXrAwI:-NMU8FbuBU9pEx0Vnk9z:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L185)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might it make more sense to use the value `null` in this case?
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.html` line 353 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMERz-F7zpuh4JrQ_4L:-NMU8YH3AGwCpQLOl1cA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L353)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

<br> elements should be avoided.
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.ts` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEXmx_CFwqIplARidn:-NMU8Zq90kXoTJXLA3ik:b-fraeru) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think institutions can be handled better:

1. There is no ADD NEW INSTITUTION item in the institutions dropdown list.
2. Instead there is an Add new institution link.
3. If you click on that link a popup with the new institution form opens.
4. When the form is submitted successfully, the popup closes, a reload of institutions is triggered and the new institution is selected.
</blockquote></details>

As per our chat, the above will be implemented as part of a new feature.
___
*[`src/app/register-user/register-user.component.ts` line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEWs-fCj9Ysg-CfTOd:-NMTpOjhAq8rkiNmWPK1:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line looks odd to me.
</blockquote></details>

Removed.
___
*[`src/app/register-user/register-user.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMENSM1Bib45lsjAkpy:-NMTj-9n4ZM3uMMLkQnE:b-92ukd) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you use a typed form group?
</blockquote></details>

My mistake, I have fixed it now.
___
*[`src/app/register-user/register-user.component.ts` line 38 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEWSvP7Bq9UkovJqGZ:-NMTj39k0ThQ_qQWtKQI:b1uhz8c) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the `submitted` variable u=is necessary. There should be a `FormGroup` flag for this.
</blockquote></details>

I agree with you, the variable is unnecessary. I don't think a flag from `FormGroup` would be necessary, I think using form controls' touched and does the trick.
___
*[`src/app/register-user/register-user.component.ts` line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEXVAzD-szG2eYrBWj:-NMTme-08RtwU-LvLFKs:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't this just be `Partner[]`?
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.ts` line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEY_OwAVEjSg9QyLJf:-NMU8q6w99AV4tJPIItj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See general comment regarding institutions above.
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.ts` line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEX8pl3UNGp5pnQj7y:-NMTqpycE3ZcLFLDr55A:b-rvihyb) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L44)):*
<details><summary><i>Previously, he [...]

2023-01-24 15:58 UTC, hettlage requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/209)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/register-user/register-user.component.html` line 155 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMESoP1CajzmFnUdz6d:-NMZQ4370z3e-TV8poJY:b-vrzki4) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L155)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Which partners are considered active? I also looked at the old WM, which shows the same list of partners as the ones displayed by the above code.
</blockquote></details>

Oh, there is indeed no way of telling from the database, it seems. Well, I guess it will have to stay the way it is for the time being then.
___
*[`src/app/register-user/register-user.component.html` line 185 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMER8MACRwfLBOXrAwI:-NMZQY2s3Mex_w9BT5MW:b-pxyfnv) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L185)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I suggested `null`, not `"null"`... :-) If you cannot set `null` as value (and that is almost undoubtedly the case), then the original `-1` is better than `"null"`, I'd say. Sorry...
___
*[`src/app/register-user/register-user.component.html` line 351 at r2](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMZOefF9CR2NobYdkFR:-NMZOefF9CR2NobYdkFS:b-ou95xk) ([raw file](https://github.com/saltastroops/web-manager/blob/6836267207b84e0dfd8e882786c39d3e0a1629d4/src/app/register-user/register-user.component.html#L351)):*
> ```HTML
>         class="button is-small"
>         [ngClass]="{ 'is-loading': loading }"
>         [disabled]="registerNewUserForm.invalid"
> ```

I wouldn't disable the submission. If you absolutely want to do this, though, you should include a message pointing out that the submission is disabled because some form content is wrong or because there are errors.
___
*[`src/app/register-user/register-user.component.scss` line 24 at r2](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMZRRRY8e5Cmygix5c8:-NMZRRRY8e5Cmygix5c9:b-mukymq) ([raw file](https://github.com/saltastroops/web-manager/blob/6836267207b84e0dfd8e882786c39d3e0a1629d4/src/app/register-user/register-user.component.scss#L24)):*
> ```SCSS
> 
> .form-group {
>   padding-bottom: 1.25rem;
> ```

You _might_ consider reducing just a tiny little bit, perhaps.
___
*[`src/app/register-user/register-user.component.ts` line 205 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEs1OXCsl1EQ_5-ljE:-NMZTbex3Wl1zF8lPBNB:b-oibhh9) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L205)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

In principle I agree with you. However the problem is the fact that the `select` element doesn't have access to the `partner` object, so it makes it a bit tricky to pass `partner.value` as a parameter instead of passing an event.
</blockquote></details>

It seems to work fine for me... The only potential issue I'd see would be handling a `null` value. But I'd think that issue exists irrespective of whether you pass the event or the select element's value.
___
*[`src/app/register-user/register-user.component.ts` line 224 at r2](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMZUmQN-2sWC-1aFdaE:-NMZUmQN-2sWC-1aFdaF:b-bwf3k9) ([raw file](https://github.com/saltastroops/web-manager/blob/6836267207b84e0dfd8e882786c39d3e0a1629d4/src/app/register-user/register-user.component.ts#L224)):*
> ```XML
>   }
> 
>   institutionsToPartners(institutions: Institution[]): Partner[] {
> ```

Maybe better "institutionsForPartners" or "partnerInstitutions" -- IMHO "institutionsToPartners" suggests a mapping from institutions to partners.


<!-- Sent from Reviewable.io -->

2023-01-25 09:27 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/209)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`src/app/register-user/register-user.component.html` line 155 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMESoP1CajzmFnUdz6d:-NMbpIuJC5x0xeYNNw3o:b-pbdqz3) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L155)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, there is indeed no way of telling from the database, it seems. Well, I guess it will have to stay the way it is for the time being then.
</blockquote></details>

Agreed.
___
*[`src/app/register-user/register-user.component.html` line 185 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMER8MACRwfLBOXrAwI:-NMc3bvq9PMOEaH7MwcQ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.html#L185)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I suggested `null`, not `"null"`... :-) If you cannot set `null` as value (and that is almost undoubtedly the case), then the original `-1` is better than `"null"`, I'd say. Sorry...
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.html` line 351 at r2](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMZOefF9CR2NobYdkFR:-NMcF8BQ2wUawyXaJswT:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/6836267207b84e0dfd8e882786c39d3e0a1629d4/src/app/register-user/register-user.component.html#L351)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wouldn't disable the submission. If you absolutely want to do this, though, you should include a message pointing out that the submission is disabled because some form content is wrong or because there are errors.
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.scss` line 24 at r2](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMZRRRY8e5Cmygix5c8:-NMcF9n97QTu-PenO6W2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/6836267207b84e0dfd8e882786c39d3e0a1629d4/src/app/register-user/register-user.component.scss#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You _might_ consider reducing just a tiny little bit, perhaps.
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.ts` line 205 at r1](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMEs1OXCsl1EQ_5-ljE:-NMbv7PYBl04vFKYPC9J:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f83f80a181f7edab85c5d225bb45988203a23ab2/src/app/register-user/register-user.component.ts#L205)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems to work fine for me... The only potential issue I'd see would be handling a `null` value. But I'd think that issue exists irrespective of whether you pass the event or the select element's value.
</blockquote></details>

Done.
___
*[`src/app/register-user/register-user.component.ts` line 224 at r2](https://reviewable.io/reviews/saltastroops/web-manager/209#-NMZUmQN-2sWC-1aFdaE:-NMbs98x1e-XuY_XE7SE:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/6836267207b84e0dfd8e882786c39d3e0a1629d4/src/app/register-user/register-user.component.ts#L224)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better "institutionsForPartners" or "partnerInstitutions" -- IMHO "institutionsToPartners" suggests a mapping from institutions to partners.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-25 10:03 UTC, hettlage approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2023-01-25 10:03 UTC, merged