block-summary-edit-button-functionality
saltastroops/web-manager pull request #292
Opened 2023-02-09 11:36 UTC by mofokeng-chaka

Functionality for editing block visit status

2023-02-09 18:36 UTC, hettlage requested changes
There should be a test for this... (Two tests even, one for the happy path and one for a failing request.)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292#-:-NNqn9X57FE_JT5Olzs5:b4cseke)* status: all files reviewed, 11 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqnj9sDX9ewKfb3fhs:-NNqnj9sDX9ewKfb3fht:b3j72b7) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L43)):*
> ```HTML
>       </th>
>       <th>Rejection Reason</th>
>       <th>Edit</th>
> ```

This button should only be visible to SALT Astronomers and admins, as only these are allowed to change the block visit status.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 122 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqp_nA2fA-QuYBJIZu:-NNqp_nA2fA-QuYBJIZv:bopcn6b) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L122)):*
> ```HTML
>         <button
>           class="button is-danger is-small"
>           [ngClass]="{ 'is-loading': loading && selectedBlockVisitId === e.id }"
> ```

Your loading variable is global, but you can click a second button while the request for the first button is still being processed. This causes problems.

Also, there is no way to add a rejection reason.

So I suspect you might rather have to use a popup window. (It might be easier to define a new component for the edit button. If so, you should check that performance doesn't suffer, though.)

Irrespective of this, I think there should be only one button, which handles both accepting and rejecting.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 127 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqrCS04PnL3bFug1HX:-NNqrCS04PnL3bFug1HY:byoz3lw) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L127)):*
> ```HTML
>           (click)="updateBlocVisitStatus($event, 'Rejected')"
>         >
>           Put block on hold
> ```

Reject
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqrJ8T9rxSa0JyjUFF:-NNqrJ8T9rxSa0JyjUFG:b-rfswwv) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L145)):*
> ```HTML
>           (click)="updateBlocVisitStatus($event, 'Accepted')"
>         >
>           Put block off hold
> ```

Accept.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 152 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqsAD7-FeqmVIgLW6m:-NNqsAD7-FeqmVIgLW6n:b-jrloxf) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L152)):*
> ```HTML
>           data-test="error"
>         >
>           {{ error }}
> ```

The same problem as for the loading variable applies to the error one.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtQwH4-_uEZQ107IT:-NNqtQwH4-_uEZQ107IU:b5u9hbe) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L97)):*
> ```XML
>   }
> 
>   updateBlocVisitStatus(
> ```

updateBlocVisitStatus > updateBlockVisitStatus
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 102 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtCfC2wQMI8Eqq07_:-NNqtCfDBtcgtUsNyaXO:b-be2746) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L102)):*
> ```XML
>   ): void {
>     const element = event.target as HTMLButtonElement;
>     const blockVisitId = parseInt(element.value);
> ```

Why don't you pass the block visit id as a function argument?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 110 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtgdb9LBhoSDIvuQb:-NNqtgdb9LBhoSDIvuQc:bkcav4y) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L110)):*
> ```XML
>         () => {
>           this.loading = false;
>           const blockVisitIndex = this.observations.findIndex(
> ```

Using the `find` method might be more idiomatic.
___
*[`src/app/service/real/real-block.service.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNrRwwE5eUceyfEbprG:-NNrRwwE5eUceyfEbprH:b-5x65r9) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/service/real/real-block.service.ts#L36)):*
> ```XML
>    * Get a block visit from the API server.
>    *
>    * If the request fails the stream terminates with a generic error message as error.
> ```

This is not correct. See, for example, the getProgressReport method of the proposal service, which actually does terminate with a generic error message.
___
*[`src/app/service/real/real-block.service.ts` line 40 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNrSYNW4IuxkIML7Suy:-NNrSYNW4IuxkIML7Suz:borp53w) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/service/real/real-block.service.ts#L40)):*
> ```XML
>    * @param id Block visit id.
>    */
>   getBlockVisit(id: number): Observable<BlockVisit> {
> ```

Is this function actually needed?
___
*[`src/app/service/real/real-block.service.ts` line 54 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNrSVEl4Umx4twse1TX:-NNrSVEm1_ZTCzz3h76A:b-5x65r9) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/service/real/real-block.service.ts#L54)):*
> ```XML
>    * Update a block visit status from the API server.
>    *
>    * If the request fails the stream terminates with a generic error message as error.
> ```

This is not correct. See, for example, the getProgressReport method of the proposal service, which actually does terminate with a generic error message.


<!-- Sent from Reviewable.io -->

2023-02-13 11:44 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqnj9sDX9ewKfb3fhs:-NO9WLBE7D5PjbOxL0T5:bkmbjqo) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This button should only be visible to SALT Astronomers and admins, as only these are allowed to change the block visit status.
</blockquote></details>

Already been implemented (check buttons' hidden attribute on the table) and it includes SALT Operators.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 122 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqp_nA2fA-QuYBJIZu:-NO9XDRj1C5QSR3hakKd:b-g436br) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L122)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Your loading variable is global, but you can click a second button while the request for the first button is still being processed. This causes problems.

Also, there is no way to add a rejection reason.

So I suspect you might rather have to use a popup window. (It might be easier to define a new component for the edit button. If so, you should check that performance doesn't suffer, though.)

Irrespective of this, I think there should be only one button, which handles both accepting and rejecting.
</blockquote></details>

I defined a new component for this functionality.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 127 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqrCS04PnL3bFug1HX:-NO9U6FOBn_wc1-c3f2s:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L127)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Reject
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqrJ8T9rxSa0JyjUFF:-NO9U5wvEEbdhVs49lWg:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Accept.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 152 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqsAD7-FeqmVIgLW6m:-NO9U7yr6sjS6LfWVpmc:btd4oiy) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L152)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The same problem as for the loading variable applies to the error one.
</blockquote></details>

I have removed this logic here. 
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtQwH4-_uEZQ107IT:-NO9USnoCeOQMs_1K-PL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

updateBlocVisitStatus > updateBlockVisitStatus
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 102 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtCfC2wQMI8Eqq07_:-NO9UX3EDANb90X4AZuC:b24pge8) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L102)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you pass the block visit id as a function argument?
</blockquote></details>

Done. And I have moved this logic to the modal component.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 110 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtgdb9LBhoSDIvuQb:-NO9XNqO7i2Cjfiq3mcE:b2f68rp) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Using the `find` method might be more idiomatic.
</blockquote></details>

In this case, I think it is better to use the `findIndex` method because I am updating a specific value(s) in an array. 
___
*[`src/app/service/real/real-block.service.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNrRwwE5eUceyfEbprG:-NO9V30iAdBVy1IrNIX_:b-uh74jy) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/service/real/real-block.service.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not correct. See, for example, the getProgressReport method of the proposal service, which actually does terminate with a generic error message.
</blockquote></details>

I see and I have removed this false information.
___
*[`src/app/service/real/real-block.service.ts` line 40 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNrSYNW4IuxkIML7Suy:-NO9VaP0AwcN5m1FuUtp:bft3c1m) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/service/real/real-block.service.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this function actually needed?
</blockquote></details>

No. I have removed it.
___
*[`src/app/service/real/real-block.service.ts` line 54 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNrSVEl4Umx4twse1TX:-NO9W-oI92IG31v_L0IN:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/service/real/real-block.service.ts#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is not correct. See, for example, the getProgressReport method of the proposal service, which actually does terminate with a generic error message.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2023-02-13 11:44 UTC, mofokeng-chaka reviewed
I am working on the tests.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292#-:-NO9_jJk9BcNRnZTF4WL:b-efaxxm)* status: 1 of 11 files reviewed, 11 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2023-02-13 15:04 UTC, hettlage requested changes
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOA8XhD11og0kEsjeZp:-NOA8XhD11og0kEsjeZq:b4oprvg) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L1)):*
> ```HTML
> <div *ngIf="isModalActive && blockVisitStatus">
> ```

* The font size might be a bit small.

* The styling of the dropdown menus is inconsistent with that of the other dropdown menus on the page.

* The modal has too much empty space.

* I'd suggest to have the buttons next to each other horizontally.

* I don't think you need colons after the labels?

* The error for the block rejection reason remains visible even if the rejection reason dropdown is hidden.

* The status is not updated after it has been changed.

* You get a block rejection reason error even if you have selected a reason.

* You get an error "No changes made to the block visit status." when you try to accept a previously rejected block.

* It might be a good idea to use Angular's reactive forms API for validating and error handling.

* When you open the modal, no values are selected. But it might be reasonable to selector the current values.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 21 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAAQcI4xNV3eMi4gdl:-NOAAQcI4xNV3eMi4gdm:b-epy95z) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L21)):*
> ```HTML
>               (change)="updateBlockVisitStatus(blockStatus.value)"
>             >
>               <option value="null"></option>
> ```

How about

```
<option selected="selected" disabled="disabled" value="null">Please select a status</option>
```
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 24 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAAk3W3oqgwnaRPGbt:-NOAAk3W3oqgwnaRPGbu:bmgq8uy) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L24)):*
> ```HTML
>               <option value="Accepted">Accepted</option>
>               <option value="Rejected">Rejected</option>
>               <option value="In queue">In queue</option>
> ```

"In queue" should not be an option.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 33 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAAb_A0SfDlUgiR-Zt:-NOAAb_A0SfDlUgiR-Zu:b56nwnb) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L33)):*
> ```HTML
>                   (change)="updateBlockRejectionReason(reason.value)"
>                 >
>                   <option value="null"></option>
> ```

How about

```
<option selected="selected" disabled="disabled" value="null">Please select a reason</option>
```
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 13 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAGqCA6pSLKcPGBLSE:-NOAGqCA6pSLKcPGBLSF:b3lvhe5) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L13)):*
> ```XML
> })
> export class EditBlockVisitStatusModalComponent {
>   @Output() blockVisitStatusEmitter = new EventEmitter<{
> ```

I would rather call this something like `blockVisitStatusUpdate`.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 48 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOACNyd6-1EJncYKajd:-NOACNyd6-1EJncYKaje:b-xqb8mo) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L48)):*
> ```XML
>   }
> 
>   updateBlockVisitStatus(blockVisitStatus: string | null): void {
> ```

Can't this be BlockVisitStatus instead of string?
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 92 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOACebU2GHedmrf3TTh:-NOACebU2GHedmrf3TTi:bchexf8) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L92)):*
> ```XML
>   }
> 
>   isSelectedStatusValid(): boolean {
> ```

The method name suggests that you are just returning the validity, but you are also updating an error.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqnj9sDX9ewKfb3fhs:-NOAEyvA8iYfHpHeOyRA:bibjl0a) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L43)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Already been implemented (check buttons' hidden attribute on the table) and it includes SALT Operators.
</blockquote></details>

a) I can see the buttons as the PI.

b) I don't think SOs are allowed to update the block status.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 110 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtgdb9LBhoSDIvuQb:-NOAFpMV1Lqq6xgj5_DY:b-ans8r8) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L110)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

In this case, I think it is better to use the `findIndex` method because I am updating a specific value(s) in an array. 
</blockquote></details>

But yiu would get the same value with `find`, so there is nil need for dealing with an index value?


<!-- Sent from Reviewable.io -->

2023-02-14 10:39 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOA8XhD11og0kEsjeZp:-NOETz5KAx-h5ybpO8W0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

* The font size might be a bit small.

* The styling of the dropdown menus is inconsistent with that of the other dropdown menus on the page.

* The modal has too much empty space.

* I'd suggest to have the buttons next to each other horizontally.

* I don't think you need colons after the labels?

* The error for the block rejection reason remains visible even if the rejection reason dropdown is hidden.

* The status is not updated after it has been changed.

* You get a block rejection reason error even if you have selected a reason.

* You get an error "No changes made to the block visit status." when you try to accept a previously rejected block.

* It might be a good idea to use Angular's reactive forms API for validating and error handling.

* When you open the modal, no values are selected. But it might be reasonable to selector the current values.


</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 21 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAAQcI4xNV3eMi4gdl:-NODpYy51Zh7jdkqOUcS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about

```
<option selected="selected" disabled="disabled" value="null">Please select a status</option>
```
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 24 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAAk3W3oqgwnaRPGbt:-NODpfcC6B7tSWXB98p3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"In queue" should not be an option.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 33 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAAb_A0SfDlUgiR-Zt:-NODpiZd6ZSuL5z1Ybou:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about

```
<option selected="selected" disabled="disabled" value="null">Please select a reason</option>
```
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 13 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOAGqCA6pSLKcPGBLSE:-NODq1Yr3V5V5Y0B1svo:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would rather call this something like `blockVisitStatusUpdate`.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 48 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOACNyd6-1EJncYKajd:-NODqQMB7n7EY0ip85Cr:b-ulib41) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can't this be BlockVisitStatus instead of string?
</blockquote></details>

No, the select element's value returns a string.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 92 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOACebU2GHedmrf3TTh:-NOEU9l1EJuqL78uW0Ua:b-l0ic8c) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The method name suggests that you are just returning the validity, but you are also updating an error.
</blockquote></details>

No longer used.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqnj9sDX9ewKfb3fhs:-NOEUK5E3i2HfHAMX8H4:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a) I can see the buttons as the PI.

b) I don't think SOs are allowed to update the block status.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 110 at r1](https://reviewable.io/reviews/saltastroops/web-manager/292#-NNqtgdb9LBhoSDIvuQb:-NODB2il8EX2o7hOVO9s:b2nnwpg) ([raw file](https://github.com/saltastroops/web-manager/blob/e2ca8a2a4cda118c8dcc050130fdc9a1992561a5/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But yiu would get the same value with `find`, so there is nil need for dealing with an index value?
</blockquote></details>

Ah, I see what you mean. I am now using `find`.


<!-- Sent from Reviewable.io -->

2023-02-15 17:56 UTC, hettlage requested changes
> Reviewed 3 of 6 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 20 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 180 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL2MhJ5Db1VHPKpXtB:-NOL2MhK4Lz_2RrO5uqQ:b-wr5ivs) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L180)):*
> ```XML
>       SummaryOfExecutedObservations.clickSubmitBlockVisitStatus();
>       // Wait for the updates
>       cy.wait(1000);
> ```

Shouldn't you wait for the request to finish rather than waiting for a specific time?
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 212 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL2x1WAiK2YHMExQIY:-NOL2x1X58VdiI9zfHQQ:bad60e9) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L212)):*
> ```XML
>     });
>     // Then user details are stored
>     userDetailsAreStored();
> ```

Is this necessary?
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 231 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL38yk8boSAU5by7NI:-NOL38yk8boSAU5by7NJ:blpqszy) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L231)):*
> ```XML
> });
> 
> describe("Block summaries - edit block visit status (PI)", () => {
> ```

PIs aren't allowed to edit the block visit status.
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 250 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL33cBCSQ53cGZbXXA:-NOL33cBCSQ53cGZbXXB:bad60e9) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L250)):*
> ```XML
>     });
>     // Then user details are stored
>     userDetailsAreStored();
> ```

Is this necessary?
___
*[`cypress/support/components/summary-of-executed-observations.ts` line 132 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOLCpQaEb8MGN-MZE0W:-NOLCpQaEb8MGN-MZE0X:b-u5bwhr) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/support/components/summary-of-executed-observations.ts#L132)):*
> ```XML
>       const text = $el.text().trim();
> 
>       // Do the assertion here
> ```

I'm not convinced this comment adds much value... :-)
___
*[`src/app/proposal/proposal.component.html` line 51 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL1kBn0jMvkSqB9aw_:-NOL1kBo8izWLoSjyFEw:bf1704f) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/proposal.component.html#L51)):*
> ```HTML
>       <wm-summary-of-executed-observations
>         [blockVisits]="p.blockVisits"
>         [investigators]="p.investigators"
> ```

You don't have to pass the investigators.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOA8XhD11og0kEsjeZp:-NOIzU1CEX-hittyWFC1:b-u629v2) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L1)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

* I  find the buttons potentially misleading, not least as they are more prominent than the icons for indicating the status. Maybe it would be better have buttons with a neutral colour and just the text "Edit"?

* There should be no Edit column if the edit buttons are hidden.

* Server errors aren't handled properly it seems. At least I don't get to see any error message.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOJ0bsA5VYFHVY14FJr:-NOJ0bsB6XtSTfAlUZ1d:b7sjeee) ([raw file](https://github.com/saltastroops/web-manager/blob/5a8d0d53ae08008a618a51838ba10840f63cb37b/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L34)):*
> ```HTML
>                 <option value="Rejected">Rejected</option>
>               </select>
>               <div
> ```

Is there any way to actually get to see this error? There should always be a block visit status be selected text.

Of course you could argue that you are coding defensively here...
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 41 at r3](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOJ13QS94_xSrhHY9jb:-NOJ13QS94_xSrhHY9jc:b-few9s6) ([raw file](https://github.com/saltastroops/web-manager/blob/5a8d0d53ae08008a618a51838ba10840f63cb37b/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L41)):*
> ```HTML
>                   *ngIf="
>                     f.blockVisitStatus.errors.required ||
>                     f.blockVisitStatus.value === null
> ```

Why do you need `f.blockVisitStatus.value === null`? What matters is only whether the value is required?
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 51 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKqp2N1kaYTmzfE9Ou:-NOKqp2N1kaYTmzfE9Ov:bmdp0do) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L51)):*
> ```HTML
>                   data-test="error"
>                 >
>                   Block visit status is required
> ```

Maybe better: Block visit > The block visit
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 78 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKr3l3-atrqzMXV2N9:-NOKr3l3-atrqzMXV2NA:bokbnwz) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L78)):*
> ```HTML
>                 </select>
>                 <div
>                   *ngIf="f.rejectionReason.touched && f.rejectionReason.errors"
> ```

See the respective comment in the TypeScript file.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 89 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKqvJv-WBgQ41dTS6o:-NOKqvJv-WBgQ41dTS6p:b-bobm2q) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L89)):*
> ```HTML
>                     data-test="error"
>                   >
>                     Block rejection reason is required
> ```

Maybe better: Block rejection reason > The block rejection reason
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 26 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKsF7K2B4LQ6nabVhV:-NOKsF7K2B4LQ6nabVhW:b-jlwxf5) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block [...]

2023-02-16 11:43 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: 6 of 15 files reviewed, 20 unresolved discussions (waiting on @hettlage)

___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 180 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL2MhJ5Db1VHPKpXtB:-NONrfHxAfAL_v_z1Syq:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L180)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you wait for the request to finish rather than waiting for a specific time?
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 212 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL2x1WAiK2YHMExQIY:-NONrgWdAPqXKbgLViGS:bwi457j) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L212)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Not anymore.
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 231 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL38yk8boSAU5by7NI:-NOOuf-I07WhHbamlrbu:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L231)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

PIs aren't allowed to edit the block visit status.
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 250 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL33cBCSQ53cGZbXXA:-NONrlHE4CDLa_onhepq:bwi457j) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L250)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this necessary?
</blockquote></details>

Not anymore.
___
*[`cypress/support/components/summary-of-executed-observations.ts` line 132 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOLCpQaEb8MGN-MZE0W:-NOOv-86DWOm4JlC6Vg5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/cypress/support/components/summary-of-executed-observations.ts#L132)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced this comment adds much value... :-)
</blockquote></details>

Done.
___
*[`src/app/proposal/proposal.component.html` line 51 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL1kBn0jMvkSqB9aw_:-NOOv11A-N6LhvML1ffo:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/proposal.component.html#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't have to pass the investigators.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOA8XhD11og0kEsjeZp:-NOOsRL40HepWr1O3aeu:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

* I  find the buttons potentially misleading, not least as they are more prominent than the icons for indicating the status. Maybe it would be better have buttons with a neutral colour and just the text "Edit"?

* There should be no Edit column if the edit buttons are hidden.

* Server errors aren't handled properly it seems. At least I don't get to see any error message.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 34 at r3](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOJ0bsA5VYFHVY14FJr:-NOOsWxL2l7dyTboNCR6:ben4lnh) ([raw file](https://github.com/saltastroops/web-manager/blob/5a8d0d53ae08008a618a51838ba10840f63cb37b/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there any way to actually get to see this error? There should always be a block visit status be selected text.

Of course you could argue that you are coding defensively here...
</blockquote></details>

No there is no way, as such I have removed this container.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 41 at r3](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOJ13QS94_xSrhHY9jb:-NOOBNih3z8XyYd5SgdW:bkd3avn) ([raw file](https://github.com/saltastroops/web-manager/blob/5a8d0d53ae08008a618a51838ba10840f63cb37b/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need `f.blockVisitStatus.value === null`? What matters is only whether the value is required?
</blockquote></details>

I have removed this container.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 51 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKqp2N1kaYTmzfE9Ou:-NOOBP6q8SBcqzeo4O6y:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Block visit > The block visit
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 78 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKr3l3-atrqzMXV2N9:-NOOB4y99IJA7dvI52Yl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the respective comment in the TypeScript file.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 89 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKqvJv-WBgQ41dTS6o:-NOOAysK6sjYDMmGi47Y:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L89)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Block rejection reason > The block rejection reason
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 26 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOKsF7K2B4LQ6nabVhV:-NONudr85PJE54O6a-gN:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`rejectionReasonNeeded` should be un [...]

2023-02-17 15:01 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 244 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUEh1BCcEMGnAoTPbp:-NOUEh1BCcEMGnAoTPbq:b-d1fn6u) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L244)):*
> ```XML
>   });
> 
>   it("should show a button for editing block visit status for a PI", () => {
> ```

should show > should not show
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 63 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHpwi321RwsiPfBE1:-NOUHpwi321RwsiPfBE2:bab9w9b) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L63)):*
> ```HTML
>                 </select>
>                 <div
>                   *ngIf="submit && editBlockVisitStatusForm.errors?.['required']"
> ```

Why not use the `touched` property of `editBlockVisitStatusForm`?
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 56 at r3](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUk-_2Cm0Xj1CE11E5:-NOUk-_2Cm0Xj1CE11E6:b-jcxqcu) ([raw file](https://github.com/saltastroops/web-manager/blob/5a8d0d53ae08008a618a51838ba10840f63cb37b/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L56)):*
> ```XML
>   ): void {
>     this.isModalActive = true;
>     this.blockVisitId = blockVisitId;
> ```

I would suggest you set `error` to `null` when opening the modal.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 33 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHkOe76ChAx9E8mzV:-NOUHkOf4Ny9gEvwaYJG:brvvc98) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L33)):*
> ```XML
>   loading = false;
>   editBlockVisitStatusForm!: FormGroup;
>   submit = false;
> ```

`submit` is not needed, I think.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 50 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUiMlN0-TbxkBDUsUy:-NOUiMlN0-TbxkBDUsUz:bfzfiwm) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L50)):*
> ```XML
>   }
> 
>   // cross-validation to ensure that rejection reason is required
> ```

Maybe better: 

```
// cross-validation to check whether a rejection reason is required
```
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 114 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUnALd1HzgvKW0x9if:-NOUnALd1HzgvKW0x9ig:b-77xnfq) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L114)):*
> ```XML
>         rejectionReason,
>       )
>       .pipe(
> ```

Not needed (see below).
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 131 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUnZJIB8pi8iOezQRZ:-NOUnZJIB8pi8iOezQR_:b58pnea) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L131)):*
> ```XML
>         },
>         (error) => {
>           this.error = error.message;
> ```

If you use `error.toString()` instead of `error.message`, there should be no need to re throw the error above,
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL-C4OBD_CUmJt11t6:-NOUoEkq1rFh378gGnGH:b65p8ao) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L37)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have removed this logic but I think I was using it because I expect to get a single user value emitted every time.
</blockquote></details>

Ah... The `take` operator closes you stream, so that you don't have to explicitly unsubscribe. So without the `take` you need to unsubscribe in `ngOnDelete` (or use the `AutoUnsubcribe` [sic] decorator in `utils.ts` for unsubscribing).

I wouldn't necessarily rely on there being only one user, give that the user might be switched without leaving the page some time in the future.
___
*[`src/app/service/real/real-block.service.ts` line 54 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUrjK3DZEuVBMKc5XP:-NOUrjK3DZEuVBMKc5XQ:b-iqjpi9) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/service/real/real-block.service.ts#L54)):*
> ```XML
>       reason: rejectionReason,
>     };
>     return this.http.patch<void>(uri, data, { headers });
> ```

I guess there is a corresponding backend change?

But I don't think the change is correct. A block visit has more details than just the block visit status and the reason (namely the night of observation, and possibly a block id). So you are not completely replacing the block, which is what PUT would suggest.


<!-- Sent from Reviewable.io -->

2023-02-17 15:07 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/service/real/real-block.service.ts` line 54 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUrjK3DZEuVBMKc5XP:-NOUuXxxAAJVjfTR6jcw:b-rue8te) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/service/real/real-block.service.ts#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess there is a corresponding backend change?

But I don't think the change is correct. A block visit has more details than just the block visit status and the reason (namely the night of observation, and possibly a block id). So you are not completely replacing the block, which is what PUT would suggest.
</blockquote></details>

Ah sorry, I missed that this was for the status, not for the visit. Oops.


<!-- Sent from Reviewable.io -->

2023-02-20 09:00 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 244 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUEh1BCcEMGnAoTPbp:-NOhG9Nx9P7RwPe1S8Ri:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L244)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

should show > should not show
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 63 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHpwi321RwsiPfBE1:-NOhGnqHDQLV6yJarUnh:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why not use the `touched` property of `editBlockVisitStatusForm`?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 56 at r3](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUk-_2Cm0Xj1CE11E5:-NOhCEwc0bX7k5-2FbPR:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/5a8d0d53ae08008a618a51838ba10840f63cb37b/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest you set `error` to `null` when opening the modal.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 33 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHkOe76ChAx9E8mzV:-NOhD53kAhw7pceFoJi3:b-w3bwza) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`submit` is not needed, I think.
</blockquote></details>

That's true. I have removed it.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 50 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUiMlN0-TbxkBDUsUy:-NOhAOVk3IEdulf4AhdY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: 

```
// cross-validation to check whether a rejection reason is required
```
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 114 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUnALd1HzgvKW0x9if:-NOhB8TO5nZMwj9pNgJe:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L114)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not needed (see below).
</blockquote></details>

Done.
___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts` line 131 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUnZJIB8pi8iOezQRZ:-NOhB9uL4OEUObA-LB7L:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.ts#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you use `error.toString()` instead of `error.message`, there should be no need to re throw the error above,
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL-C4OBD_CUmJt11t6:-NOhFsNr0EIVxkBuRWQF:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah... The `take` operator closes you stream, so that you don't have to explicitly unsubscribe. So without the `take` you need to unsubscribe in `ngOnDelete` (or use the `AutoUnsubcribe` [sic] decorator in `utils.ts` for unsubscribing).

I wouldn't necessarily rely on there being only one user, give that the user might be switched without leaving the page some time in the future.
</blockquote></details>

Done.
___
*[`src/app/service/real/real-block.service.ts` line 54 at r2](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUrjK3DZEuVBMKc5XP:-NOhBOwj64jEhia_8wik:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0ce180068c6aa6bef32fefead7318965669ea56f/src/app/service/real/real-block.service.ts#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah sorry, I missed that this was for the status, not for the visit. Oops.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-20 10:17 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 63 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHpwi321RwsiPfBE1:-NOiHoIY1mLTxMfW2XrN:b-wqygoj) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L63)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If you use the `touched` property of the `rejectionReaon` component, you can experience some inconsistency:

1. Edit an accepted observation.
2. Change Accepted to Rejected ---> NO ERROR IS SHOWN
3. Click the Submit button
4. Close the modal
5. Edit another accepted observation.
6. Change Accepted to Rejected ---> AN ERROR IS SHOWN
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL-C4OBD_CUmJt11t6:-NOiJrbHDXU4jdZMKg8M:bc396lj) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L37)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think you are unsubscribing...
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 35 at r6](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOiJnDPCIXbPjHUIVWj:-NOiJnDPCIXbPjHUIVWk:bsezq3b) ([raw file](https://github.com/saltastroops/web-manager/blob/9ae359af8beebfca37338f59bb79d63ef5735034/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L35)):*
> ```XML
>       .getUser()
>       .pipe(
>         catchError((e) => {
> ```

Is this `catchError` actually required?


<!-- Sent from Reviewable.io -->

2023-02-20 11:06 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 63 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHpwi321RwsiPfBE1:-NOiTaEl8EljtLv9aeBu:bd4cgfh) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you use the `touched` property of the `rejectionReaon` component, you can experience some inconsistency:

1. Edit an accepted observation.
2. Change Accepted to Rejected ---> NO ERROR IS SHOWN
3. Click the Submit button
4. Close the modal
5. Edit another accepted observation.
6. Change Accepted to Rejected ---> AN ERROR IS SHOWN
</blockquote></details>

I don't experience the same issue as you. It made more sense to me to throw an error only if the user tries to submit the rejected status without selecting the rejected reason. In my case, I consistently experience the following:

1. Edit an accepted observation
2. Change Accepted to Rejected ---> NO ERROR IS SHOWN (as intended)
3. Click Submit button ---> Error: The block rejection reason is required
4. Close the modal
5. Edit another accepted observation
6. Change Accepted to Rejected ---> NO ERROR IS SHOWN (as intended)
7. Click Submit button ---> Error: The block rejection reason is required
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 37 at r4](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOL-C4OBD_CUmJt11t6:-NOiSpVd4Ho-Ee1104T-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/058fdea9f097666d977e1c16b1cb4fa9f67c845c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you are unsubscribing...
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 35 at r6](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOiJnDPCIXbPjHUIVWj:-NOiUbzuC5U-BT7YTVDN:b2nhky0) ([raw file](https://github.com/saltastroops/web-manager/blob/9ae359af8beebfca37338f59bb79d63ef5735034/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this `catchError` actually required?
</blockquote></details>

No.


<!-- Sent from Reviewable.io -->

2023-02-23 07:35 UTC, hettlage requested changes
I'm a bit reluctant to accept the PR without any test... :-(

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292#-:-NOxBCuV6iVTULf4gkXM:b8tpxef)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 63 at r5](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOUHpwi321RwsiPfBE1:-NOxAKQ54QAvK1ZazMeC:b-cu9kp5) ([raw file](https://github.com/saltastroops/web-manager/blob/aa3f55c9e87132ab2f99dd37eea003574d604f0e/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L63)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I don't experience the same issue as you. It made more sense to me to throw an error only if the user tries to submit the rejected status without selecting the rejected reason. In my case, I consistently experience the following:

1. Edit an accepted observation
2. Change Accepted to Rejected ---> NO ERROR IS SHOWN (as intended)
3. Click Submit button ---> Error: The block rejection reason is required
4. Close the modal
5. Edit another accepted observation
6. Change Accepted to Rejected ---> NO ERROR IS SHOWN (as intended)
7. Click Submit button ---> Error: The block rejection reason is required
</blockquote></details>

Well, I tried again and cannot reproduce the issue.


<!-- Sent from Reviewable.io -->

2023-02-23 08:08 UTC, hettlage approved these changes
Oops. I was just blind.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292#-:-NOxIwHmC_joXUqlB_6c:bk3s8md)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2023-02-23 11:51 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 85 at r8](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOxx-h-0F414j07gNF9:-NOy6DgJ6WvGkHdTWG7N:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a7005d37877a972964442f92e6d51863861b1589/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I had missed that earlier, but having the submit button outside the form IMHO is not ideal.

See my respective comments on the the edit-block-status PR.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 07:44 UTC, hettlage requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 85 at r8](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOxx-h-0F414j07gNF9:-NPGnJSJANF_mEwjls67:b-6wbkdc) ([raw file](https://github.com/saltastroops/web-manager/blob/a7005d37877a972964442f92e6d51863861b1589/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L85)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems I wasn't clear :( I was not objecting to the layout (which I think looked better before the latest changes), but to the fact that the submit button was outside the <form> element. So I'd suggest you just move the form tag and make the necessary css changes.


<!-- Sent from Reviewable.io -->

2023-02-27 12:42 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: 18 of 21 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 85 at r8](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOxx-h-0F414j07gNF9:-NPHt20AD3YUGMfaJh_A:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a7005d37877a972964442f92e6d51863861b1589/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems I wasn't clear :( I was not objecting to the layout (which I think looked better before the latest changes), but to the fact that the submit button was outside the <form> element. So I'd suggest you just move the form tag and make the necessary css changes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-28 08:05 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html` line 85 at r8](https://reviewable.io/reviews/saltastroops/web-manager/292#-NOxx-h-0F414j07gNF9:-NPM2UYOAeOhljfi59he:b-ucfknh) ([raw file](https://github.com/saltastroops/web-manager/blob/a7005d37877a972964442f92e6d51863861b1589/src/app/proposal/general/edit-block-visit-status-modal/edit-block-visit-status-modal.component.html#L85)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[`src/app/service/real/real-block.service.ts` line 54 at r10](https://reviewable.io/reviews/saltastroops/web-manager/292#-NPM2ODRD829iXoYjNHd:-NPM2ODRD829iXoYjNHe:b-rv142d) ([raw file](https://github.com/saltastroops/web-manager/blob/3ff756bf77044306993b637cdb4b2e130251c0f0/src/app/service/real/real-block.service.ts#L54)):*
> ```XML
>       reason: rejectionReason,
>     };
>     return this.http.put<void>(uri, data, { headers });
> ```

Doesn't that have to be `patch` now?


<!-- Sent from Reviewable.io -->

2023-02-28 08:12 UTC, mofokeng-chaka reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/service/real/real-block.service.ts` line 54 at r10](https://reviewable.io/reviews/saltastroops/web-manager/292#-NPM2ODRD829iXoYjNHd:-NPM3FXR7m4rBqcGkaxd:b-n7600p) ([raw file](https://github.com/saltastroops/web-manager/blob/3ff756bf77044306993b637cdb4b2e130251c0f0/src/app/service/real/real-block.service.ts#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Doesn't that have to be `patch` now?
</blockquote></details>

That's true, I have updated it.


<!-- Sent from Reviewable.io -->

2023-02-28 09:38 UTC, hettlage approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)



<!-- Sent from Reviewable.io -->

2023-02-28 09:39 UTC, merged