Creating a proposal status update
saltastroops/web-manager pull request #293
Opened 2023-02-13 19:11 UTC by Eb-Zeero

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltastroops/web-manager/293)

2023-02-20 12:36 UTC, hettlage requested changes
> Reviewed 4 of 12 files at r1, 7 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 18 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/blocks/block/block.component.ts` line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOLDRVS0Nb1DbacCp5y:-NOLDRVTEQQxj93QhMLW:b-u9yenw) ([raw file](https://github.com/saltastroops/web-manager/blob/bde287ae161d819999bca029c473f8166a3fa362/src/app/proposal/blocks/block/block.component.ts#L26)):*
> ```XML
>     this.validFrom = jd.start;
>     this.validUntil = jd.end;
>     console.log("$$$: ", this.block);
> ```

Unnecessary log statement
___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 107 at r1](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOLDUMI7Eyx1Uaujfaa:-NOLDUMI7Eyx1Uaujfab:b-u9yenw) ([raw file](https://github.com/saltastroops/web-manager/blob/bde287ae161d819999bca029c473f8166a3fa362/src/app/proposal/blocks/block-view/block-view.component.ts#L107)):*
> ```XML
>   selectBlock(block: BlockSummary): void {
>     this.selectedBlock = block;
>     console.log(block);
> ```

Unnecessary log statement
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 46 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOikk6r3qJVq-BAnCxd:-NOikk6r3qJVq-BAnCxe:b3j3h62) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L46)):*
> ```HTML
>               (click)="
>                 proposalStatusCommentModal.openProposalStatusCommentModal(
>                   'Inactive',
> ```

Should be Under technical review, not Inactive.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 55 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOil39i5Y2Uazdvm3PJ:-NOil39i5Y2Uazdvm3PK:b-zo9je) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L55)):*
> ```HTML
>             <button
>               *ngIf="
>                 selectedStatus !== 'Active' &&
> ```

Should be `selectedStatus === 'Under technical review'`.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 127 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOioOFZBFf_dgEMO5dA:-NOioOFZBFf_dgEMO5dB:b-v1zygm) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L127)):*
> ```HTML
>           <label for="self-activatable"
>             ><input
>               *ngIf="!loading"
> ```

Isn't `loading` indicating that there is a proposal status request?
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 131 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOin66R-iaKESmdZUwS:-NOin66R-iaKESmdZUwT:b3ioxb5) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L131)):*
> ```HTML
>               id="self-activatable"
>               [ngClass]="
>                 loading ? 'loading checkbox is-large' : ' checkbox is-large'
> ```

Obsolete space between `'` and `checkbox`
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 151 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOinnbO11vF3IxSlZUs:-NOinnbO11vF3IxSlZUt:b-m9h37f) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L151)):*
> ```HTML
>               *ngIf="selfActivatableResults.display"
>             >
>               Updated Successfully!
> ```

It seems you alway display the same text, irrespective of whether the request was successful?
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOLGcqM5hj_MuPYWa8l:-NOLGcqM5hj_MuPYWa8m:b-g7yth0) ([raw file](https://github.com/saltastroops/web-manager/blob/bde287ae161d819999bca029c473f8166a3fa362/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L16)):*
> ```XML
>   child: any;
>   @ViewChild(ProposalStatusReasonModalComponent)
>   set WM(child: ProposalStatusReasonModalComponent) {
> ```

Why the name "WM"?
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 14 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiYYsMD4ps9NSPEeTN:-NOiYYsMD4ps9NSPEeTO:b7cdy5x) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L14)):*
> ```XML
> export class DetailsTableComponent implements OnChanges, OnInit {
>   @Input() proposal!: Proposal;
>   child: any;
> ```

Why `any`? Shouldn't this be `ProposalStatusCommentModalComponent`?
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 23 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiYtXc6bFd7xIcuIjD:-NOiYtXc6bFd7xIcuIjE:bfhl84c) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L23)):*
> ```XML
>   isPiOrPc = false;
>   isSelfActivatable!: boolean;
>   selfActivatableResults: {
> ```

I think TypeScript can infer the type from the initial value.

More importantly, the various variables and their names to  me suggest that there is too much functionality in this component and that there should be child components for the proposal status and the self activatable status,
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 55 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOibvEQD4yqtMHPeuF5:-NOibvEQD4yqtMHPeuF6:bl9hp77) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L55)):*
> ```XML
>     this.isSelfActivatable = this.proposal.generalInfo.isSelfActivatable;
>     this.statusComment = this.proposal.generalInfo.status.comment;
>     const user = sessionStorage.getItem("user");
> ```

This might not be the best way of getting the user. (There is an RxJS stream for that -- technically the user might change.)
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 61 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOimMgz5K_iaqPXExyF:-NOimMgz5K_iaqPXExyG:b-hrsh8n) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L61)):*
> ```XML
>       );
>       this.isPiOrPc = ["Principal Contact", "Principal Investigator"].some(
>         (r) => JSON.parse(user).roles.includes(r),
> ```

I don't think this is correct, as the PI / PC role depends on the proposal code. So you'll have to get this information from the proposal object.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 83 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiXbJPCtFVtBBFsrP1:-NOiXbJPCtFVtBBFsrP2:bat4tvc) ([raw file](https://github.com/saltastroops/web-ma [...]

2023-02-22 20:26 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: 3 of 30 files reviewed, 18 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 46 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOikk6r3qJVq-BAnCxd:-NOnwLjkAtSseh0fjnvX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be Under technical review, not Inactive.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 55 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOil39i5Y2Uazdvm3PJ:-NOnwMQN1acIzIEvZB5M:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be `selectedStatus === 'Under technical review'`.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 127 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOioOFZBFf_dgEMO5dA:-NOnwvZB7gwec-4N-DFp:b-4gynec) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L127)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't `loading` indicating that there is a proposal status request?
</blockquote></details>

No, that request is made on the modal.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 131 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOin66R-iaKESmdZUwS:-NOnx2ob8Yek9M5aaRmn:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L131)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Obsolete space between `'` and `checkbox`
</blockquote></details>

removed
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 151 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOinnbO11vF3IxSlZUs:-NOtqRhV5c5wt9wHEdNK:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems you alway display the same text, irrespective of whether the request was successful?
</blockquote></details>

fixed
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOLGcqM5hj_MuPYWa8l:-NOnyQcy1Lw5iHc7QW1I:bhwx0w9) ([raw file](https://github.com/saltastroops/web-manager/blob/bde287ae161d819999bca029c473f8166a3fa362/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the name "WM"?
</blockquote></details>

it can be any name the body should return the correct child
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 14 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiYYsMD4ps9NSPEeTN:-NOtqXNS8feuOm8h-4zL:b-9p1lrv) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why `any`? Shouldn't this be `ProposalStatusCommentModalComponent`?
</blockquote></details>

it should be that extending to something not sure what is it.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 23 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiYtXc6bFd7xIcuIjD:-NOokmsD2PxKLTjxKEVz:b2filjo) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think TypeScript can infer the type from the initial value.

More importantly, the various variables and their names to  me suggest that there is too much functionality in this component and that there should be child components for the proposal status and the self activatable status,
</blockquote></details>

splited
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 55 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOibvEQD4yqtMHPeuF5:-NOtsDDl3KI-6Wixerr9:b-9m9ix3) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might not be the best way of getting the user. (There is an RxJS stream for that -- technically the user might change.)
</blockquote></details>

Can you please help with this
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 61 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOimMgz5K_iaqPXExyF:-NOtt-jI9dSrSRelfnPu:b-phmap9) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this is correct, as the PI / PC role depends on the proposal code. So you'll have to get this information from the proposal object.
</blockquote></details>

Yes, you are correct. missed it.
is there a way to check this?
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 83 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiXbJPCtFVtBBFsrP1:-NOtqqZYAaNftN9hJPqk:bt2vr1b) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a problem here: If you change the status and then close the comment modal, the "new" value is still shown, even though the status hasn't been updated on the backend.
</blockquote></details>

Fixed.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 113 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiePdf6e3q30ogRT3f:-NOtr1ZxBBV_02exWyJ-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L113)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

updated > update

In this case you should revert to the old value, and I'd suggest not to hide the failure message again.
</blockquote></details>

Done.
___
*[`src/app/types/proposal.ts` line 204 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiiLjbB-RRRVTspFs0:- [...]

2023-02-23 15:59 UTC, hettlage requested changes
> Reviewed 27 of 27 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 22 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOLGcqM5hj_MuPYWa8l:-NOyzLIh0L_5YYpY0VTo:b-9qmw47) ([raw file](https://github.com/saltastroops/web-manager/blob/bde287ae161d819999bca029c473f8166a3fa362/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L16)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it can be any name the body should return the correct child
</blockquote></details>

Yes, but the name should indicate what the variable is about. :-)
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyjvmaCGSilfnQN-Vh:-NOyjvmaCGSilfnQN-Vi:b-p4bhi4) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html#L1)):*
> ```HTML
> <wm-proposal-status-comment-modal
> ```

When I close the modal without submitting, the value in the drop down menu is not reverted.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html` line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOykYiQ1H7OsopwWPbR:-NOykYiQ1H7OsopwWPbS:b-nvo373) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html#L10)):*
> ```HTML
>   <select
>     id="proposal-status"
>     (change)="statusChange($event)"
> ```

It might be easier to give the component a name (`#status`) and then to pass the value (`status.value`) rather than the event.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html` line 39 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyiiFs6uvbdDVf0Spk:-NOyiiFt7GXJPatJduOV:b-fj6xrh) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html#L39)):*
> ```HTML
>     Deactivate
>   </button>
>   <!--  && proposal.generalInfo.isSelfActivatable-->
> ```

This check is missing now...
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts` line 53 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOykx8J8qL3y3j9NZ0Z:-NOykx8J8qL3y3j9NZ0_:b-hsu7uu) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts#L53)):*
> ```XML
>     this.statusComment = this.proposal.generalInfo.status.comment;
>   }
>   statusChange(event: Event): void {
> ```

There should be an empty line between the methods.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 6 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyouTL-35fMeFJB83d:-NOyouTL-35fMeFJB83e:b-v6lb5r) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L6)):*
> ```HTML
>   [ngClass]="!isUpdated && displayUpdateMessage ? 'has-text-danger' : ''"
>   ><input
>     *ngIf="!loading"
> ```

The component should still be shown during loading (you disable it anyway).
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypFD2AUtbS_-YXRxY:-NOypFD2AUtbS_-YXRxZ:b-9t4iww) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L13)):*
> ```HTML
>     [disabled]="loading"
>   />
>   <button
> ```

Showing a small loading spinner is a good idea, but I don't think you should display a button.

Also, I would put it after the checkbox label, not before.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypqQ59_9LVHIy56jF:-NOypqQ59_9LVHIy56jG:b1kc8te) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L18)):*
> ```HTML
>     class="button is-loading is-small"
>   ></button>
>   The PI/PC may activate the proposal
> ```

Shouldn't this be a label?
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts` line 16 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyrh8k2Y05aA38KVNF:-NOyrh8l7R30jLDw-wOn:bjqvfu4) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts#L16)):*
> ```XML
>   updateMessage = "";
>   isUpdated = false;
>   displayUpdateMessage = false;
> ```

Isn't this variable unnecessary? You can just check whether there is a message?
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 7 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytmSw9aE_WFhX6sUS:-NOytmSw9aE_WFhX6sUT:b-uonqes) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L7)):*
> ```HTML
>   <tr *ngIf="isSaOrAdmin">
>     <td>
>       <div class="select" *ngIf="!loading">
> ```

The dropdown menu should be disabled during loading, but it should still be shown.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 8 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOysJ660YlJJQ74c2U4:-NOysJ660YlJJQ74c2U5:bk53jg3) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L8)):*
> ```HTML
>     <td>
>       <div class="select" *ngIf="!loading">
>         <select id="salt-astronomers" (change)="saltAstronomerChange($event)">
> ```

See the above comment on using the value rather than $event.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytX5-0YEovuMK51ad:-NOytX5-0YEovuMK51ae:bmfjiam) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L9)):*
> ```HTML
>       <div class="select" *ngIf="!loading">
>         <select id="salt-astronomers" (change)="saltAstronomerChange($event)">
>           <option *ngIf="!selectedSaltAstronomerId">None</option>
> ```

`None` is a perfectly valid option, which should always be shown.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 20 at r4](https://revi [...]

2023-02-27 19:47 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: 18 of 31 files reviewed, 22 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOLGcqM5hj_MuPYWa8l:-NP1NsXz3oeWsPFANUlD:b-5whiwl) ([raw file](https://github.com/saltastroops/web-manager/blob/bde287ae161d819999bca029c473f8166a3fa362/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, but the name should indicate what the variable is about. :-)
</blockquote></details>

renamed and moved
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html` line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyjvmaCGSilfnQN-Vh:-NPJBgOmCHnRmHmrapDT:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

When I close the modal without submitting, the value in the drop down menu is not reverted.
</blockquote></details>

fixed
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html` line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOykYiQ1H7OsopwWPbR:-NPJBmaVD5iYBX5AMcjL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be easier to give the component a name (`#status`) and then to pass the value (`status.value`) rather than the event.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html` line 39 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyiiFs6uvbdDVf0Spk:-NPGsLmQDBX_B5Tocn8G:b-7jc0aw) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.html#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This check is missing now...
</blockquote></details>

sorry
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts` line 53 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOykx8J8qL3y3j9NZ0Z:-NPGsT4_1gpVJ9--V4GE:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be an empty line between the methods.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 6 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyouTL-35fMeFJB83d:-NPIzBAH-i4NoKnN_fW_:b-1ay9y8) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The component should still be shown during loading (you disable it anyway).
</blockquote></details>

showing
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypFD2AUtbS_-YXRxY:-NPIxZJY54Gtz3C-i3a5:b-hw3r35) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Showing a small loading spinner is a good idea, but I don't think you should display a button.

Also, I would put it after the checkbox label, not before.
</blockquote></details>

For, a checkbox and a radio button are not Ideal for it being on the right... and all the checkboxes are on the left of the text.
to add I will be fighting bulma for this comment
button removed
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypqQ59_9LVHIy56jF:-NPIzVjSEF7d8_NWfPCQ:bcvrwq3) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be a label?
</blockquote></details>

it is a label moved p tag outside of the label
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts` line 16 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOyrh8k2Y05aA38KVNF:-NPIzdor3Zfl1in1kfnY:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this variable unnecessary? You can just check whether there is a message?
</blockquote></details>

removed
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 7 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytmSw9aE_WFhX6sUS:-NPJ0v7IEcCxBjvNIYCj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The dropdown menu should be disabled during loading, but it should still be shown.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 8 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOysJ660YlJJQ74c2U4:-NPJ0wQv24C_J2r40iSe:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the above comment on using the value rather than $event.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytX5-0YEovuMK51ad:-NPJ190H6ml8AIIX7D3-:b-rfdekp) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`None` is a perfectly valid option, which should always be shown.
</blockquote></details>

for the case, you are not the SA or Admin and there is no liaison astronomer yet
___
*[`src/app [...]

2023-02-28 11:11 UTC, hettlage requested changes
> Reviewed 1 of 27 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 28 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypFD2AUtbS_-YXRxY:-NPJUT0RDc_B6DcbB7Z3:b-s63o9u) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L13)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

For, a checkbox and a radio button are not Ideal for it being on the right... and all the checkboxes are on the left of the text.
to add I will be fighting bulma for this comment
button removed
</blockquote></details>

I'm not sure what you mean. But I see no problem with the loading spinner being to the right of the label.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypqQ59_9LVHIy56jF:-NPJUnEv7Sc6oZk3SP68:bomdrbs) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L18)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it is a label moved p tag outside of the label
</blockquote></details>

Ah sorry, I hadn't seen the label tag.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts` line 20 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMZteE8meXOjl1MxX0:-NPMZteE8meXOjl1MxX1:b8bhf3n) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts#L20)):*
> ```XML
> 
>   changeSelfActivatable(): void {
>     this.loading = true;
> ```

You should reset the `updateMessage`.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 7 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytmSw9aE_WFhX6sUS:-NPMeA8f7VJ1X1c1XavX:b-vr9hhm) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L7)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It isn't disabled. (You have to replace the `[disabled]` with `[attr.disabled]`, as you did elsewhere.)
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytX5-0YEovuMK51ad:-NPMfyHT48Y6mj4mxJ3T:b3kre) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L9)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

for the case, you are not the SA or Admin and there is no liaison astronomer yet
</blockquote></details>

?
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts` line 50 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMdfZ1A6r2MPCbwCBH:-NPMdfZ1A6r2MPCbwCBI:b8bhf3n) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts#L50)):*
> ```XML
> 
>     this.proposalService
>       .updateLiaisonAstronomer(this.proposal.proposalCode, currentSaId)
> ```

You should reset the `updateMessage`.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts` line 29 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMgNxx38VAp4MtXLbk:-NPMgNxx38VAp4MtXLbl:b2o1utw) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts#L29)):*
> ```XML
>     private saltAstronomersService: SaltAstronomersService,
>     private proposalService: ProposalService,
>     public fb: FormBuilder,
> ```

Shouldn't this be private?
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMhJAv9Ph64Av_dN_G:-NPMhJAv9Ph64Av_dN_H:b-2mpod9) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts#L70)):*
> ```XML
>           this.loading = false;
>           this.isUpdated = true;
>           this.updateMessage = "Updated successfully!";
> ```

You also have to update the `initialSaltAstronomerId`.
___
*[`src/app/service/salt-astronomers.service.ts` line 20 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMb_905IqHhkn04uKV:-NPMb_9112jEmE-ku65y:bh2fjjs) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/service/salt-astronomers.service.ts#L20)):*
> ```XML
>    */
>   getSaltAstronomers(): Observable<UserListItem[]> {
>     const uri = environment.apiUrl + "/salt-astronomers";
> ```

Theres must be a trailing slash, as otherwise the SALT Astronomers won't load due to a CORS error.
___
*[`src/app/types/proposal.ts` line 204 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiiLjbB-RRRVTspFs0:-NPMbt6W-vET1F0icEqV:b5023vr) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/types/proposal.ts#L204)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But you haven't renamed the type yet... :-)
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 72 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOynFeg9KtOBREQtsqF:-NPJV2sqDUQHpfwBGktR:b2dq4tu) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L72)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I need to show a success message it is now a second with a green background.
</blockquote></details>

Let's discuss this.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMSROH82au6CPUB1M5:-NPMSROH82au6CPUB1M6:bhc1y4w) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L1)):*
> ```HTML
> <div *ngIf="isModalActive">
> ```

There might be a bit much empty space in the modal.
___
*[`src/app/proposal/general/proposal-details/details-tab [...]

2023-02-28 11:44 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 29 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMpB1F69Dm6rci8PDg:-NPMpB1F69Dm6rci8PDh:b-nv98wg) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L1)):*
> ```HTML
> <table class="table">
> ```

I just realised there is a problem. If the liaison astronomer is an ex-SALT Astronomer, you won't display the name. So I guess the better approach will be to handle the updating in a modal.


<!-- Sent from Reviewable.io -->

2023-03-02 19:03 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 29 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypFD2AUtbS_-YXRxY:-NPXYEhVEtzfnlG1Mfcb:b-ygu9t) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure what you mean. But I see no problem with the loading spinner being to the right of the label.
</blockquote></details>

this will be the only check box that is rightly aligned. I can  not make this special
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 18 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypqQ59_9LVHIy56jF:-NPXTqPFBXW4eCAoBpQ9:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah sorry, I hadn't seen the label tag.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts` line 20 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMZteE8meXOjl1MxX0:-NPXU8HZ-jfyuELt9tSk:b-cypuid) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should reset the `updateMessage`.
</blockquote></details>

updating
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 7 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytmSw9aE_WFhX6sUS:-NPXY4DIEx7w-V-bbwb-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It isn't disabled. (You have to replace the `[disabled]` with `[attr.disabled]`, as you did elsewhere.)
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOytX5-0YEovuMK51ad:-NPXVI9k-cSJTwGP6DCN:bjz4xpt) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

?
</blockquote></details>

sorry I was adding not in your state meant like
`None isn't  a perfectly valid option, which shouldn't be shown.`
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMpB1F69Dm6rci8PDg:-NPYWhrhAbc4cwUzF1yI:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I just realised there is a problem. If the liaison astronomer is an ex-SALT Astronomer, you won't display the name. So I guess the better approach will be to handle the updating in a modal.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts` line 50 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMdfZ1A6r2MPCbwCBH:-NPXW2L_7_b9Bfg1xFZH:biij3de) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should reset the `updateMessage`.
</blockquote></details>

it is been updated or I am missing something?
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts` line 29 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMgNxx38VAp4MtXLbk:-NPXVhs2E7e1_AxXENa_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be private?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts` line 70 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMhJAv9Ph64Av_dN_G:-NPXWm9J2qq3sR70FPKk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You also have to update the `initialSaltAstronomerId`.
</blockquote></details>

Done.
___
*[`src/app/service/salt-astronomers.service.ts` line 20 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMb_905IqHhkn04uKV:-NPXX1la3Ap4nztA7dVR:b-mf6hkz) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/service/salt-astronomers.service.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Theres must be a trailing slash, as otherwise the SALT Astronomers won't load due to a CORS error.
</blockquote></details>

this only affect you in my case it is fine
___
*[`src/app/types/proposal.ts` line 204 at r3](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOiiLjbB-RRRVTspFs0:-NPXXKHe4RzXKmc_rdX-:b-lw7w6i) ([raw file](https://github.com/saltastroops/web-manager/blob/11702594ecdb3f2cca59b35d23d570006c6bce18/src/app/types/proposal.ts#L204)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you haven't renamed the type yet... :-)
</blockquote></details>

missed activation
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 72 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOynFeg9KtOBREQtsqF:-NPX8FdoBT2qybDBlM8H:b-qssebl) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Let's discuss this.
</blockquote></details>

fixed.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMSROH82au6CPUB1M5:-NPX3irK00xmLv48g687:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03 [...]

2023-03-08 12:28 UTC, hettlage requested changes
> Reviewed 14 of 21 files at r6, 11 of 15 files at r7, 4 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: 34 of 42 files reviewed, 36 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 43 at r6](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPYnzHw5qqBQarg_hNn:-NPYnzHxEu0uwwjO91UP:by7hdn6) ([raw file](https://github.com/saltastroops/web-manager/blob/f67208fa9c3a796b72ffd66cf44f1fcaaf874ee6/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L43)):*
> ```XML
>     this.statSwitch(status);
>   }
>   statSwitch(status: string): void {
> ```

statSwitch > updateStatusDetails
___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 94 at r6](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPYp-MD2ewaM5hu8lq9:-NPYp-MD2ewaM5hu8lqA:b-nb3vn1) ([raw file](https://github.com/saltastroops/web-manager/blob/f67208fa9c3a796b72ffd66cf44f1fcaaf874ee6/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L94)):*
> ```XML
> 
>   ngDoCheck(): void {
>     this.statSwitch(this.proposal.generalInfo.status.value);
> ```

I guess the answer is yes, but I ask just in case: Is `ngDoCheck` required?
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 31 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-hTGG6yat2wWP2vD9:-NQ-hTGG6yat2wWP2vDA:b-dpajh5) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L31)):*
> ```XML
>     this.authService.user().subscribe(
>       (user) => {
>         if (user) {
> ```

You are not handing the case that the user us null.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts` line 36 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-hmsx338aBIrP3A8C:-NQ-hmsx338aBIrP3A8D:b-v8z4yx) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts#L36)):*
> ```XML
>     this.authService.user().subscribe(
>       (user) => {
>         if (user) {
> ```

You aren't handling the case that the user is null.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypFD2AUtbS_-YXRxY:-NPYtmdF-cGvJ4ZJhL3V:biqy2zf) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L13)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this will be the only check box that is rightly aligned. I can  not make this special
</blockquote></details>

I didn't mean that the checkbox should be to the right, I meant that there should be a loading spinner next to the label text.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMpB1F69Dm6rci8PDg:-NPMpzb7-axUzyAzjcds:b-5b3d7e) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I just realised there is a problem. If the liaison astronomer is an ex-SALT Astronomer, you won't display the name. So I guess the better approach will be to handle the updating in a modal.
</blockquote></details>

I do wonder whether we should have a dedicated modal component. I'll raise an issue for that, and i yiu prefer you can use raise an issue for moving the liaison SA update to a modal.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 1 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-pyPZ9Gp5wwn1-5T4:-NQ-pyPZ9Gp5wwn1-5T5:b-kjp8s4) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L1)):*
> ```HTML
> <div *ngIf="isModalActive">
> ```

There is too much empty space in the modal.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-uoZx-zFAMihkqzpf:-NQ-uoZx-zFAMihkqzpg:bne82tw) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L34)):*
> ```HTML
>                 [attr.disabled]="loading ? '' : null"
>               >
>                 <option value="null">None</option>
> ```

I think an empty string rather than "null" would be better.

And it seems the bottom corners aren't rounded.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 1 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-tvrb4AeUt8ShF7pQ:-NQ-tvrb4AeUt8ShF7pR:bb1ukdx) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L1)):*
> ```XML
> import { Component, Input, OnInit } from "@angular/core";
> ```

Naming is a bit inconsistent. You have both "responsible" and "liaison" in file and directory names.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 21 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-rLR37WWFboHDh5ZO:-NQ-rLR37WWFboHDh5ZP:b2wdv51) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L21)):*
> ```XML
>   initialSaltAstronomerId: string | null = null;
>   isUpdated = false;
>   updateMessage: string | null = null;
> ```

Do you really need this? You only show a message in case of an error (and then calling it error might be better).

Note that there should be different errors for loading the astronomers and submitting.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-rrDzD0Rsc0Qb6o-u:-NQ-rrDzD0Rsc0Qb6o-v:b-9usczv) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L34)):*
> ```XML
> 
>   ngOnInit(): void {
>     this.loading = true;
> ```

I'd argue that you should have two different loading variables, as the loading of SALT Astronomers and the submission should be handled differently in the modal.

(The same is true for the errors.)
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 43 at r7](https://revi [...]

2023-03-08 15:25 UTC, Eb-Zeero reviewed
Count down Arboted...

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293#-:-NQ0opbz01zP3pzNXcVn:b-6jjxj3)* status: 34 of 42 files reviewed, 33 unresolved discussions (waiting on @hettlage and @output)

___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 43 at r6](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPYnzHw5qqBQarg_hNn:-NQ0W2-z41A32LlTKy-X:b6g18ob) ([raw file](https://github.com/saltastroops/web-manager/blob/f67208fa9c3a796b72ffd66cf44f1fcaaf874ee6/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

statSwitch > updateStatusDetails
</blockquote></details>

not in use any more
___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 94 at r6](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPYp-MD2ewaM5hu8lq9:-NQ0W8rT1RAoE6M0wMB1:badqlyw) ([raw file](https://github.com/saltastroops/web-manager/blob/f67208fa9c3a796b72ffd66cf44f1fcaaf874ee6/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess the answer is yes, but I ask just in case: Is `ngDoCheck` required?
</blockquote></details>

DoCheck removed
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 31 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-hTGG6yat2wWP2vD9:-NQ0WQV970rSae7WI6XD:b-boz9ha) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are not handing the case that the user us null.
</blockquote></details>

I assume the user is logged in and has to be logged in to get here... if not, the user can't be admin, SA,  PC or, PI
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts` line 36 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-hmsx338aBIrP3A8C:-NQ0XQSQEjTJ3ZjzsRye:b-hs0sua) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status.component.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't handling the case that the user is null.
</blockquote></details>

see the above comment,
I do not want to verify if a user is logged in here.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 13 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NOypFD2AUtbS_-YXRxY:-NQ0ddSuAChQVNYHNMkW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I didn't mean that the checkbox should be to the right, I meant that there should be a loading spinner next to the label text.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMpB1F69Dm6rci8PDg:-NQ0dy1m5yuwwNuQHfg4:b2otwf9) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/responsible-astronomer/responsible-astronomer.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I do wonder whether we should have a dedicated modal component. I'll raise an issue for that, and i yiu prefer you can use raise an issue for moving the liaison SA update to a modal.
</blockquote></details>

this is now done it is done in the modal
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 1 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-pyPZ9Gp5wwn1-5T4:-NQ0iqIK1ChitFOMrDhq:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is too much empty space in the modal.
</blockquote></details>

fixed
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-uoZx-zFAMihkqzpf:-NQ0jXlD-HkndbsxuKJs:bxcdf3b) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think an empty string rather than "null" would be better.

And it seems the bottom corners aren't rounded.
</blockquote></details>

count down 10...
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 1 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-tvrb4AeUt8ShF7pQ:-NQ0k7J4-1arIgTfpaYH:b-hff6wv) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Naming is a bit inconsistent. You have both "responsible" and "liaison" in file and directory names.
</blockquote></details>

renamed
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 21 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-rLR37WWFboHDh5ZO:-NQ0kbDBAPZeyExgrUDl:b-df3d51) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really need this? You only show a message in case of an error (and then calling it error might be better).

Note that there should be different errors for loading the astronomers and submitting.
</blockquote></details>

Not really nice catch
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 34 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-rrDzD0Rsc0Qb6o-u:-NQ0ksgg9E-T-vY35y-9:b-om1xq0) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd argue that you should have two different loading variables, as the loading of SALT Astronomers and the submission should be handled differently in the modal.

(The same is true for the errors.)
</blockquote></details>

I do not see why they should be different.
Can we discuss this
___
*[`src/app/proposal/genera [...]

2023-03-08 18:46 UTC, hettlage requested changes
> Reviewed 5 of 12 files at r8, 17 of 17 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 15 unresolved discussions (waiting on @Eb-Zeero and @output)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 31 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-hTGG6yat2wWP2vD9:-NQ1GvMF5LZENRPpBZSI:bowbjs9) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L31)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I assume the user is logged in and has to be logged in to get here... if not, the user can't be admin, SA,  PC or, PI
</blockquote></details>

You have a point, given that the relevant variables have a default value of false.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 14 at r9](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1SIey0babQbBCNUB4:-NQ1SIey0babQbBCNUB5:bc0vj18) ([raw file](https://github.com/saltastroops/web-manager/blob/8b0298abbf64d42f98731cf136a63661541a8840/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L14)):*
> ```HTML
>   />
>   The PI/PC may activate the proposal
>   <div *ngIf="loading" class="control is-loading"></div>
> ```

I don't think a div within a label is allowed. 
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts` line 20 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMZteE8meXOjl1MxX0:-NQ1Tm-71E7K4hwfttm0:bmdpjpp) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts#L20)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

updating
</blockquote></details>

What I meant is that you should reset the message before you make the backend request.
___
*[`src/app/utils.ts` line 304 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1XX2f6MeOvAs1qCPV:-NQ1XX2f6MeOvAs1qCPW:b-jh36sj) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/utils.ts#L304)):*
> ```XML
>   investigators: Investigator[],
> ): boolean {
>   return investigators.some((i) => i.id == user.id && i.isPc);
> ```

Why did you replace `===`with `==`?
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMSROH82au6CPUB1M5:-NQ1L1cODvwujtuWwhJA:bp386ge) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I deny this comment, please show me!
</blockquote></details>

![screenshot\_303.png](https://files.reviewableusercontent.io/images/reviewable/11633365/sFSsn8s3vVhj7bKvgd7APwgn/screenshot_303.png)
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 30 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMRqtkCrxeFhPQ---O:-NQ1L8pp1NbfSQC1bVto:bvh6p0d) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L30)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Yes, We can discuss it.
PI/PC has two options Activate or Deactivate but admins/SA has a range so it can't be handled the same.
</blockquote></details>

I think it can. But let's discuss.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts` line 92 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-m8OhCQmYP6BVwke3:-NQ1MMAB8FziHPlrM3jl:b-d48eve) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts#L92)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

closeModat is the @Output() of this function
</blockquote></details>

That ia a good reason not to call the method `closeModal'. But you could call it `close` or `closeStatusModal`. I wouldn't call it `closeStatusCommentModal, given the modal is for the status rather than status comment.

I would not rename the @Output.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts` line 109 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-msm9CWPPn8_ty7GE:-NQ1MzwY8GiFz4c0i24h:b-p9uknk) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts#L109)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

is it because we shouldn't trust that the backend will do its job?
</blockquote></details>

Yes. If something goes wrong, the user should know.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts` line 32 at r9](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1LVpcDIKzPHZxW_Jy:-NQ1LVpd2ihbAw17nG4w:bq8rwga) ([raw file](https://github.com/saltastroops/web-manager/blob/8b0298abbf64d42f98731cf136a63661541a8840/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts#L32)):*
> ```XML
> export class ProposalStatusModalComponent {
>   @Input() proposal!: Proposal;
>   @Output() closeStatusCommentModal: EventEmitter<string> = new EventEmitter();
> ```

Why not just `closeModal`?
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 29 at r9](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1UR5v9YNLYe2o2QzA:-NQ1UR5w8AmTPuDv4zVV:b-qyje6i) ([raw file](https://github.com/saltastroops/web-manager/blob/8b0298abbf64d42f98731cf136a63661541a8840/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L29)):*
> ```HTML
>                 [attr.disabled]="loading ? '' : null"
>               >
>                 <option [value]="">None</option>
> ```

Do you really need the square brackets? And shouldn't that be `[value]="''"`?
___
*[`src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 1 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-pyPZ9Gp5wwn1-5T4:-NQ1UsPm2bY7_d7FvPmM:b1y9zge) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/responsible-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wro [...]

2023-03-09 18:54 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: 34 of 47 files reviewed, 15 unresolved discussions (waiting on @hettlage and @output)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 31 at r7](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-hTGG6yat2wWP2vD9:-NQ4WcYK7HQH45os8hJ5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/2490022509046dae33329e0952d763aa6d0d9b4a/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You have a point, given that the relevant variables have a default value of false.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html` line 14 at r9](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1SIey0babQbBCNUB4:-NQ6ensZ3JtwBwKfSnwn:bfslzkh) ([raw file](https://github.com/saltastroops/web-manager/blob/8b0298abbf64d42f98731cf136a63661541a8840/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.html#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think a div within a label is allowed. 
</blockquote></details>

Moved out side now
___
*[`src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts` line 20 at r4](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMZteE8meXOjl1MxX0:-NQ6f9-V2rI0YsPxxy8i:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8aba9e913da495226c04eebb095f08fc7e03ac70/src/app/proposal/general/proposal-details/details-table/self-activate/self-activate.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What I meant is that you should reset the message before you make the backend request.
</blockquote></details>

Done.
___
*[`src/app/utils.ts` line 304 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1XX2f6MeOvAs1qCPV:-NQ6g2ly6p3LI3N_lsrq:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/utils.ts#L304)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you replace `===`with `==`?
</blockquote></details>

fixed
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 1 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMSROH82au6CPUB1M5:-NQ6Q2_4EzboJSCYAQiH:b-886gsx) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

![screenshot\_303.png](https://files.reviewableusercontent.io/images/reviewable/11633365/sFSsn8s3vVhj7bKvgd7APwgn/screenshot_303.png)
</blockquote></details>

Fixed
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html` line 30 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMRqtkCrxeFhPQ---O:-NQ6eE0x76cF2TswFUCA:b-gf6jfq) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.html#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it can. But let's discuss.
</blockquote></details>

discussed
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.ts` line 125 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMV6C9ELBH9IniZlHT:-NQ6ehEg2Zkx2aeGl6Gv:b-buucpc) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.ts#L125)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

please let's Discuss
</blockquote></details>

discussed
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.ts` line 129 at r5](https://reviewable.io/reviews/saltastroops/web-manager/293#-NPMVEaK0ekvs1pqEyqh:-NQ6ek2u6jgWZ3S38chx:bl40imo) ([raw file](https://github.com/saltastroops/web-manager/blob/1d77c03f2ec1be7fb9bcd072c2dbb75b4d0d95f3/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-comment-modal/proposal-status-comment-modal.component.ts#L129)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

please let's Discuss
</blockquote></details>

Discussed
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts` line 92 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-m8OhCQmYP6BVwke3:-NQ6eZv90ij7Txf84VCt:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That ia a good reason not to call the method `closeModal'. But you could call it `close` or `closeStatusModal`. I wouldn't call it `closeStatusCommentModal, given the modal is for the status rather than status comment.

I would not rename the @Output.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts` line 109 at r8](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ-msm9CWPPn8_ty7GE:-NQ6eeqNAEsGco5yjz8M:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f32380aa9a5c779883c7d233a20510f9ccf8dbfe/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes. If something goes wrong, the user should know.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts` line 32 at r9](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1LVpcDIKzPHZxW_Jy:-NQ6eWcxEImby1XVnojn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8b0298abbf64d42f98731cf136a63661541a8840/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why not just `closeModal`?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 29 at r9](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQ1UR5v9YNLYe2o2QzA:-NQ6fGk_7AUI9_FgJKSl:bfzwh8e) ([raw file](https://github.com/saltastroops/web-manager/blob/8b0298abbf64d42f98731cf136a63661541a8840/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockq [...]

2023-03-10 13:42 UTC, hettlage requested changes
> Reviewed 13 of 13 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.scss` line 19 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAjGZB7vcJXpGMdQnU:-NQAjGZB7vcJXpGMdQnV:bu971eo) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.scss#L19)):*
> ```SCSS
> }
> 
> .modal-card-foot {
> ```

model-card-foot > model-card-footer

(also true everywhere else, I'd guess)
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html` line 51 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAenTb-9Ah6hPoPlbQ:-NQAenTb-9Ah6hPoPlbR:b-h2lvun) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html#L51)):*
> ```HTML
>             </div>
>             <div class="field">
>               <label class="label">Proposal Status comment(optional)</label>
> ```

"comment(optional)" > "comment (optional)"
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html` line 125 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAdOTmCyJUKe3RUvsp:-NQAdOTn2FO4341imifK:bbijx97) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html#L125)):*
> ```HTML
>               "
>             >
>               {{ updateMessage }}
> ```

The message should have a slight padding on the left, and it should be entered vertically relative to the buttons.
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 44 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAj0Qj-WklzwllipzO:-NQAj0Qj-WklzwllipzP:b-6cuoxw) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L44)):*
> ```HTML
>           </div>
>         </section>
>         <section *ngIf="updateError" class="modal-card-body">
> ```

I don't think an error should have a separate section?
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 48 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAiew22UYwA4pJc7js:-NQAiew22UYwA4pJc7jt:b-xgiuch) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L48)):*
> ```HTML
>             <div class="control">
>               <p class="invalid-feedback has-text-danger">
>                 {{ updateError }}
> ```

This error is located in the modal footer in the proposal status modal, and I'd say this is where it should be placed.
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 99 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAk74o07uRiB6JkEIH:-NQAk74o07uRiB6JkEII:bqkqqi6) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L99)):*
> ```XML
>         () => {
>           this.isUpdated = false;
>           this.updateError = "Failed to update liaison SALT astronomer!";
> ```

update liaison > update the liaison


<!-- Sent from Reviewable.io -->

2023-03-10 14:54 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.scss` line 19 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAjGZB7vcJXpGMdQnU:-NQB-qIeB3e7QRk1vhGD:bpyz7vq) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.scss#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

model-card-foot > model-card-footer

(also true everywhere else, I'd guess)
</blockquote></details>

No can't do that is a Bulma class name 
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html` line 51 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAenTb-9Ah6hPoPlbQ:-NQAzMQv7FCaneyRe0Ey:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"comment(optional)" > "comment (optional)"
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html` line 125 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAdOTmCyJUKe3RUvsp:-NQB-a3l98PSzQEGMbte:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/details-table/proposal-status/proposal-status-modal/proposal-status-modal.component.html#L125)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The message should have a slight padding on the left, and it should be entered vertically relative to the buttons.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 44 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAj0Qj-WklzwllipzO:-NQB-alp1WTZXlk5UnGa:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think an error should have a separate section?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html` line 48 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAiew22UYwA4pJc7js:-NQB-ddB77ZDI004C93N:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.html#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This error is located in the modal footer in the proposal status modal, and I'd say this is where it should be placed.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts` line 99 at r10](https://reviewable.io/reviews/saltastroops/web-manager/293#-NQAk74o07uRiB6JkEIH:-NQB07fd7IczgkoAthgl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/abbc7a479da1f64a16d7d15e8ab952692ce0166b/src/app/proposal/general/proposal-details/liaison-astronomer/liaison-astronomer-modal/liaison-astronomer-modal.component.ts#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

update liaison > update the liaison
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-10 15:47 UTC, hettlage approved these changes
> Reviewed 6 of 6 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-03-10 15:49 UTC, merged