Request data
saltastroops/web-manager pull request #324
Opened 2023-03-28 20:35 UTC by Eb-Zeero

2023-03-29 10:59 UTC, hettlage requested changes
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/324)* status: 9 of 10 files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 206 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRguieD4lYman-CGzRT:-NRguieD4lYman-CGzRU:b-8vtgy4) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L206)):*
> ```HTML
>   </tbody>
> </table>
> <div class="field is-pulled-right">
> ```

The checkbox and submit button should be hidden if the table of observations is hidden.

There should be some space between the checkbox and the button.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 205 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgxDWx28w6ZnbPFPK8:-NRgxDWx28w6ZnbPFPK9:b-cb0u9e) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L205)):*
> ```XML
>       }
>     });
>     const requestedDataFormats = ["all"];
> ```

Should be "All"
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 207 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgxFPX9_dE1C0yRMPL:-NRgxFPX9_dE1C0yRMPM:b-jo6cez) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L207)):*
> ```XML
>     const requestedDataFormats = ["all"];
>     if (this.includeCalibrations) {
>       requestedDataFormats.push("calibration");
> ```

Should be "Calibration"
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 229 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRh-vGN3zaNODX7CjXM:-NRh-vGN3zaNODX7CjXN:bw9v89j) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L229)):*
> ```XML
>   }
> 
>   canRequestData(): boolean {
> ```

I'm a bit apprehensive of conditionally disabled buttons. It might be better to rather show an error if the button is pressed without anything having been selected.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 239 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgxbP65KaHxlGUf2Xw:-NRgxbP65KaHxlGUf2Xx:bd0zph7) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L239)):*
> ```XML
>   }
> 
>   toggleIncludeCalibrations(checked: boolean): void {
> ```

Nit-picking, I know, but you are not toggling, you are setting.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 245 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgy4OB7xbP2m8_tkPE:-NRgy4OB7xbP2m8_tkPF:b-oq7xta) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L245)):*
> ```XML
>   clearRequestedData(): void {
>     this.includeCalibrations = false;
>     this.observations.map((o) => {
> ```

This is a case for `forEach` rather than `map`.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 247 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgyMMN2uI9CNZkHP7K:-NRgyMMN2uI9CNZkHP7L:bd0zph7) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L247)):*
> ```XML
>     this.observations.map((o) => {
>       if (o.downloadObservation) {
>         this.toggleRequestData(false, o.id);
> ```

Nit-picking, I know, but you are not toggling, you are setting.
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgyqNFEeutB5uUyZUB:-NRgyqNFEeutB5uUyZUC:b-5x0nd1) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html#L1)):*
> ```HTML
> <div *ngIf="isModalActive">
> ```

You are not indicating whether spectrophotometric standards were included.
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html` line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgz4V19VGwEPNjpPHi:-NRgz4V2CEuLWi6P2YVl:b-fxnjch) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html#L2)):*
> ```HTML
> <div *ngIf="isModalActive">
>   <div class="modal" [ngClass]="isModalActive ? 'is-active' : ''">
> ```

You might consider hiding the table if no observations have been requested.
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html` line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgylCl7r3Up-ijMaCa:-NRgylCl7r3Up-ijMaCb:b-dgi4ij) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html#L16)):*
> ```HTML
>         </header>
>         <section class="modal-card-body">
>           <label class="label">Proposal Status comment (optional)</label>
> ```

Unnecessary label
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html` line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgyQw_5puFmC7ZEI8l:-NRgyQw_5puFmC7ZEI8m:bl1ogo5) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html#L22)):*
> ```HTML
>                 <th>Observation Id</th>
>                 <th>Observation Name</th>
>                 <th>Accepted?</th>
> ```

I'm not convinced the "Accepted?" column should be included. It might easily be misinterpreted as "Has your request been successful?".
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.ts` line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgzuv50U1Tmf1BSp6x:-NRgzuv50U1Tmf1BSp6y:b-ano9wp) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.ts#L12)):*
> ```XML
> export class DownloadObservationsModalComponent {
>   @Input() observations!: Observation[] [...]

2023-03-30 11:40 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/324)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 206 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRguieD4lYman-CGzRT:-NRm-dZh660C0ZqWOg6U:bd5m49f) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L206)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

But do we really need the hiding link now?
</blockquote></details>

That is another question, of course. Wasn't the plan to remove it in a separate PR?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 210 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmFPAC5SkhRkaCkNm3:-NRmFPAC5SkhRkaCkNm4:bc05d6x) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L210)):*
> ```HTML
>     </tbody>
>   </table>
>   <div class="field is-pulled-right">
> ```

The section is jumping if the error message is (too) long.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 239 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm-ukF4WklHYLM4lbV:-NRm-ukF4WklHYLM4lbW:b1h40vc) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L239)):*
> ```HTML
>       </div>
>     </div>
>     <div class="field" *ngIf="error">
> ```

You get no error if the server is down.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 239 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmCRa17oi2zteGPpNI:-NRmCRa17oi2zteGPpNJ:b-p2m2uc) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L239)):*
> ```HTML
>       </div>
>     </div>
>     <div class="field" *ngIf="error">
> ```

The font size of the error message is too small.

Also, this div is overlapping with the heading of the next section.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 242 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm-OR3-3-VsZI4rFbl:-NRm-OR3-3-VsZI4rFbm:b-dr3oe4) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L242)):*
> ```HTML
>       <div class="control">
>         <p class="invalid-feedback has-text-danger">
>           {{ error }} error next here
> ```

I guess "error next here" should not be there?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 245 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgy4OB7xbP2m8_tkPE:-NRmHmXCCvaOfal90A8Z:b-vnzd9h) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L245)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

sorry missing  = now fixed
</blockquote></details>

But now there's another problem. Your `map` has a side effect (as you call `this.toggleRequestData`), and you wouldn't expect that.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 33 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm1QtP3Vr5IbZTbbN7:-NRm1QtQ1H3nPl7VcMRs:blviabd) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L33)):*
> ```XML
>   @Input() proposalCode!: string;
>   @Output() selectBlock = new EventEmitter<number>();
>   downloadObservationModal!: any;
> ```

any > DownloadObservationsModalComponent ?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm1Y9O92jrcnoL70bq:-NRm1Y9O92jrcnoL70br:b5rtymz) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L49)):*
> ```XML
>   selectedSemesters = new Set<string>();
>   requestingData = false;
>   error: string | null = "Not yet an error";
> ```

Why do you set the initial value to a string rather than `null`?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm6-gn07geqpiIUAxi:-NRm6-gn07geqpiIUAxj:b-nmj3bu) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L173)):*
> ```XML
> 
>   isAllDataSelected(): boolean {
>     this.error = null;
> ```

This line shouldn't be here. (You wouldn't expect the error to be reset in a getter method. Also, it breaks error handling.)
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 203 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmCrPh33IjwZMprgIH:-NRmCrPh33IjwZMprgII:b-ayvyje) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L203)):*
> ```XML
>     this.error = null;
>     if (!this.includeCalibrations && !this.anySelectedData()) {
>       this.error = "No Data selected.";
> ```

Rather than having a lengthy `else` block, you might just return in case of an error.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 203 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmD0mT4QHFVuJ1Lton:-NRmD0mT4QHFVuJ1Ltoo:bnuzyzt) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L203)):*
> ```XML
>     this.error = null;
>     if (!this.includeCalibrations && !this.anySelectedData()) {
>       this.error = "No Data selected.";
> ```

"No data selected and no spectrophotometric standards requested."
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 233 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmETkM3nfLMcMLeR9U:-NRmETkM3nfLMcMLeR9V:b483dla) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L233)):*
> ```XML
>           () => {
>             this.requestingData = false;
>             this.error = "Fai [...]

2023-03-30 15:37 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/324)* status: all files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 206 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRguieD4lYman-CGzRT:-NRmPhO6Al2clVg4NxgZ:b6pwf7x) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L206)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That is another question, of course. Wasn't the plan to remove it in a separate PR?
</blockquote></details>

Yes it is.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 210 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmFPAC5SkhRkaCkNm3:-NRmz1Q68_2qoBMvCG7-:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L210)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The section is jumping if the error message is (too) long.
</blockquote></details>

fixed
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 239 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmCRa17oi2zteGPpNI:-NRn4WJ-BPJ0crjFAHkg:b-ipyu1t) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L239)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The font size of the error message is too small.

Also, this div is overlapping with the heading of the next section.
</blockquote></details>

introdused flex
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 239 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm-ukF4WklHYLM4lbV:-NRn9Wrn-dWAQp01VdGJ:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L239)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You get no error if the server is down.
</blockquote></details>

fixed
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 242 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm-OR3-3-VsZI4rFbl:-NRmlt_-CEQJD4EMRqH2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L242)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess "error next here" should not be there?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 245 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgy4OB7xbP2m8_tkPE:-NRmvbFm0MiSmia_42MT:b-wi65dt) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L245)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But now there's another problem. Your `map` has a side effect (as you call `this.toggleRequestData`), and you wouldn't expect that.
</blockquote></details>

the old web manager clears all selected data that is what I do as well
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 33 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm1QtP3Vr5IbZTbbN7:-NRmuQgSAZ8_OJHZYcbz:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

any > DownloadObservationsModalComponent ?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm1Y9O92jrcnoL70bq:-NRmuh7I-qUsPbGb8aKb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you set the initial value to a string rather than `null`?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 173 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRm6-gn07geqpiIUAxi:-NRmuqYy9GRGo4qzfhcC:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L173)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line shouldn't be here. (You wouldn't expect the error to be reset in a getter method. Also, it breaks error handling.)
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 203 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmCrPh33IjwZMprgIH:-NRmv1gp11zWuQ3A4Nbh:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L203)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Rather than having a lengthy `else` block, you might just return in case of an error.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 203 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmD0mT4QHFVuJ1Lton:-NRmv89k2TtdnW6o27kI:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L203)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"No data selected and no spectrophotometric standards requested."
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 233 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmETkM3nfLMcMLeR9U:-NRmvD_eCwxVWC_dMxPx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Your data request has failed."
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 235  [...]

2023-03-31 16:44 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/324)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 239 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmCRa17oi2zteGPpNI:-NRsWaW4A3FycjN21Uh7:b-auvne1) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L239)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still think the font size is a bit small. And it might be helpful if the text was bold.
</blockquote></details>

Set to 1em
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 245 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgy4OB7xbP2m8_tkPE:-NRsX5WmE4bn6nLmg86t:btrepke) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L245)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wasn't commenting about the fact that you clear the selected data, but about how you do it. Maybe it's easier to resolve this in person?
</blockquote></details>

forEach used now
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html` line 16 at r2](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRmIoNf70GbGUvyfubS:-NRsXb1W7CJ7n3AprYl-:bs2m6l3) ([raw file](https://github.com/saltastroops/web-manager/blob/fe426972468cd14282d6fea61902489620b5539c/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.html#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Which should have a bottom margin -- I think it's too close to the table.
</blockquote></details>

margin added
___
*[`src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.ts` line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager/324#-NRgzuv50U1Tmf1BSp6x:-NRsYCdK1M2BYAYEIdDL:b-6jgksn) ([raw file](https://github.com/saltastroops/web-manager/blob/7d7cb5b1dc66b9764baae2a3ccce8266eedac0ca/src/app/proposal/general/summary-of-executed-observations/download-observations-modal/download-observations-modal.component.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you could still use that as the event name, I'd guess, by passing the name to the Output directive (and then choose a variable name like `_closeModal` or `closeModalEvent`).
</blockquote></details>

We need to set ts lint first to allow an alias 


<!-- Sent from Reviewable.io -->

2023-04-03 09:44 UTC, hettlage reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/324)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2023-04-03 09:45 UTC, merged