Progress report
saltastroops/web-manager pull request #85
Opened 2021-11-29 08:42 UTC by Eb-Zeero

2021-12-02 08:17 UTC, hettlage requested changes
> Reviewed 18 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/85)* status: 18 of 26 files reviewed, 28 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/util.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MppwtgY7Zh4eXB_eU6w:-MppwtgY7Zh4eXB_eU6x:b-exobnq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/util.ts#L13)):*
> ```XML
>    The given datetime must be timezone-aware.
>    */
>   const shifted = addHours(addMinutes(t, t.getTimezoneOffset()), 12)
> ```

I don't think you need getTimezoneOffset, and (judging from the demo in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset) it is a treacherous friend.

I would suggest to use the getUTCMonth and getUTCFull method of the Date class instead.

And yes, this function. is an excellent candidate for a unit test... ;-)
___
*[src/app/util.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MppzNw0DBnt2-3HHquJ:-MppzNw0DBnt2-3HHquK:b-17l6o4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/util.ts#L22)):*
> ```XML
>     semester = 2
>   }
>   if (semester === 0 ) {
> ```

This might not be necessary; semester cannot be 0.
___
*[src/app/util.ts, line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MppzfAk9xiLixbGs_3l:-MppzfAk9xiLixbGs_3m:b-8z5g9d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/util.ts#L25)):*
> ```XML
>     throw new Error("Semester couldn't be determined.")
>   }
>   return `${shifted.getFullYear()}-${semester}`
> ```

You get the wrong year for January to April.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 4 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq0C5u7GC_Xuus-YlJ:-Mpq0C5u7GC_Xuus-YlK:b-1kw6sn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L4)):*
> ```HTML
> <wm-requested-observing-conditions></wm-requested-observing-conditions>
> <div class="progress-report-form">
>   <h2 class="title is-5">Requests for next semester {{nextSemester}}</h2>
> ```

The alignment between the input fields and the labels seems to be slightly broken, in particular if there are error messages.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq15gA72wkLNvKrswN:-Mpq15gA72wkLNvKrswO:bb71uiu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L32)):*
> ```HTML
>             data-test="error"
>           >
>             Requested time is required
> ```

Requested > The requested
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1Q-hE_ZOulxJdrcn:-Mpq1Q-hE_ZOulxJdrco:b-rcvlau) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L97)):*
> ```HTML
>             data-test="error"
>           >
>             Maximum seeing is required
> ```

Maximum > The maximum
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 108 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq4xmo3DP0r-5PG0HJ:-Mpq4xmo3DP0r-5PG0HK:bpbtr4p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L108)):*
> ```HTML
>         <div class="has-two-columns thirty-ten">
>           <div class="select">
>             <select (change)="changeTransparency($event)" formControlName="transparency">
> ```

I don't think you have to explicitly listen to cha
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 123 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1Tsv-C9wxauJd1dS:-Mpq1Tsv-C9wxauJd1dT:b-tfx5lg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L123)):*
> ```HTML
>             data-test="error"
>           >
>             Transparency is required
> ```

Transparency > The transparency
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 151 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1aUO6lkyHzjWDJHQ:-Mpq1aUO6lkyHzjWDJHR:bvmhfvm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L151)):*
> ```HTML
>             data-test="error"
>           >
>             Description of observing constraints is required
> ```

Description > The description
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 162 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1ufk9cY5DTUfyOZI:-Mpq1ufk9cY5DTUfyOZJ:bpm7o95) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L162)):*
> ```HTML
>         <div>
>           <div>
>             <textarea
> ```

You can reduce the height of this and the following two text areas by a factor of 2.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqLPXK4Hd7AIB3mDXf:-MpqLPXK4Hd7AIB3mDXg:bq62nuq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L1)):*
> ```XML
> import {Component, Input, OnInit} from '@angular/core';
> ```

I think the overall structure might need some discussion.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqLVGE2rOWKl_5hpTJ:-MpqLVGE2rOWKl_5hpTK:bxquwjc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L43)):*
> ```XML
>       transparency: ['', Validators.required],
>       descriptionOfObservingConstraints: ['', Validators.required],
>       whyTimeRequestChanged: ['', Validators.required],
> ```

This oil only required if the requested time actually changed.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 49 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqFLJx4dgUa2d-y0Q8:-MpqFLJx4dgUa2d-y0Q9:b-ktrezi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L49)):*
> ```XML
>     this.nextSemester = nextSemester()
>     this.proposalService.getProposalPartners(this.proposal.proposalCode).subscribe(
>         (data: any) => {
> ```

Shouldn't be any.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 56 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqFNurE8kszmH4uu3U:-MpqFNurE8kszmH4uu3V:b7nrqsa) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/ [...]

2022-01-21 10:24 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/85)* status: 10 of 30 files reviewed, 28 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 4 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq0C5u7GC_Xuus-YlJ:-MtGyVhh6fgR7y1_9U1s:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The alignment between the input fields and the labels seems to be slightly broken, in particular if there are error messages.
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq15gA72wkLNvKrswN:-Msd7rWpCSAlbbXZKfc0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Requested > The requested
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1Q-hE_ZOulxJdrcn:-Msd7zMx8njlpgw9pOLp:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maximum > The maximum
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 108 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq4xmo3DP0r-5PG0HJ:-MttK3E92Z-pO-bzWbrf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you have to explicitly listen to cha
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 123 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1Tsv-C9wxauJd1dS:-Msd88o48rVZA0canvT0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Transparency > The transparency
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 151 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1aUO6lkyHzjWDJHQ:-Msd8H7G3tIsLJmOiWo0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L151)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Description > The description
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 162 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpq1ufk9cY5DTUfyOZI:-Msd9E1j2mAUEoe0Ghja:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You can reduce the height of this and the following two text areas by a factor of 2.
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqLPXK4Hd7AIB3mDXf:-MtvphtF5NW5ID-8Lm-W:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the overall structure might need some discussion.
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqLVGE2rOWKl_5hpTJ:-Mtw9TavAxFQfEqBt1V_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This oil only required if the requested time actually changed.
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 49 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqFLJx4dgUa2d-y0Q8:-Mtvpn4U8RJOY_bTgU2j:bb7k6nd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't be any.
</blockquote></details>

lost
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 56 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqFNurE8kszmH4uu3U:-Mtvpo5DAiPK3spnzGsE:bb7k6nd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't be any, if possible.
</blockquote></details>

lost
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 110 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqMAU_00CnTZMm1GiJ:-Mtw9VzF2Dx41YEIldtM:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This commented out code might have to be deleted?
</blockquote></details>

Done.
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqMIph6xh2hZAlfysJ:-Mtw24b66zr07QMRBQKy:bb7k6nd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This method should be unnecessary.
</blockquote></details>

lost
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 150 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqM_rAE96vaBzRwb3t:-Mtw23VOEH4-2o7fIYxw:bb7k6nd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L150)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This method might be unnecessary?
</blockquote></details>

lost
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 157 at r1](https://reviewable.io/reviews/saltastroops/web-manag [...]

2022-01-21 10:25 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/85)* status: 10 of 30 files reviewed, 28 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/proposal/general/proposal-progress-table/proposal-progress-table.component.html, line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpu8H8cCTiDU76Hel2F:-Mtw9lCN9oyTqU_eQ1XE:bmjnzdv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/proposal-progress-table/proposal-progress-table.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What do you mean? Can't you get them from the proposal?
</blockquote></details>

no can't


<!-- Sent from Reviewable.io -->

2022-01-21 10:26 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/85)* status: 10 of 30 files reviewed, 28 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/util.ts, line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MppwtgY7Zh4eXB_eU6w:-Mtw9sVN3BHYX4ZLy9OP:b2kf6uz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/util.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need getTimezoneOffset, and (judging from the demo in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset) it is a treacherous friend.

I would suggest to use the getUTCMonth and getUTCFull method of the Date class instead.

And yes, this function. is an excellent candidate for a unit test... ;-)
</blockquote></details>

can we discuss this again
___
*[src/app/util.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MppzNw0DBnt2-3HHquJ:-Mtw9xONDPdV5bc4Kk2V:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/util.ts#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This might not be necessary; semester cannot be 0.
</blockquote></details>

removed
___
*[src/app/service/real/real-proposal.service.ts, line 99 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-Mpu9d_T6Pko4mLTgDRc:-Mtw9pR2EWifgutXjNyC:bb7k6nd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/service/real/real-proposal.service.ts#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this function necessary?
</blockquote></details>

lost


<!-- Sent from Reviewable.io -->

2022-01-24 14:47 UTC, hettlage requested changes
> Reviewed 3 of 17 files at r3, 37 of 37 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/85)* status: all files reviewed, 20 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/utils.spec.ts, line 53 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAmHRsC-Eif9RFeSWZ:-MuAmHRsC-Eif9RFeSW_:b-7bqdcd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/utils.spec.ts#L53)):*
> ```XML
> 
> 
> describe('semesterOfDatetime return the correct semester', () => {
> ```

It might be better to use a library like date-fns with human-friendly datetime strings rather than the Date constructor.

Also you might test that the semester transition happens at noon.

Also note that some tests are failing now, given I've changed the semesterOfDatetime function (taking into account that months are zero-offset in JS).
___
*[src/app/proposal/general/proposal-progress/proposal-progress.component.ts, line 38 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAs5eABxQYq01fn4Yw:-MuAs5eABxQYq01fn4Yx:bqhyce7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L38)):*
> ```XML
> 
>     this.proposalService
>       .getProgressReport('2020-1-MLT-005', '2021-1')
> ```

Hardcoded proposal code and semester
___
*[src/app/proposal/general/proposal-progress/proposal-progress.component.ts, line 41 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAsVN-8t5EMNGNHyAn:-MuAsVN-8t5EMNGNHyAo:bidxzg7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L41)):*
> ```XML
>       .subscribe(
>         (data) => {
>           this.progressReport = {
> ```

Why don't you just say `this.progressReport = data` (or, if you prefer, `this.progressReport = {...data}`?
___
*[src/app/proposal/general/proposal-progress/proposal-progress.component.ts, line 56 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAsyeE5AmX9cJwuZrC:-MuAsyeE5AmX9cJwuZrD:b96kvxb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L56)):*
> ```XML
>         },
>         (error) => {
>           if (error.status === 401) {
> ```

Isn't this caught by the AuthenticationInterceptor service?
___
*[src/app/proposal/general/proposal-progress/requests-next-semester/previous-time-requests.component.html, line 4 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB87eg2oY_2eKKM4sb:-MuB87eg2oY_2eKKM4sc:bmo4xno) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/requests-next-semester/previous-time-requests.component.html#L4)):*
> ```HTML
> <!--ToDO-->
> <div class="progress-report-form">
>   <h2 class="title is-5">Requests for next semester {{ semester }}</h2>
> ```

The requests for the next semester should not be handled in a component called previous-time-requests
___
*[src/app/service/real/real-proposal.service.ts, line 103 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuBW9GYEN8v8DMKiGg7:-MuBW9GYEN8v8DMKiGg8:b-jan2ho) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/service/real/real-proposal.service.ts#L103)):*
> ```XML
>         camelcaseKeys(progressReport, { deep: true })
>       ),
>       catchError(() => {
> ```

Catching an error here might not be ideal, as you lose information about errors caught by the authentication interceptor service, I think.
___
*[src/app/types/proposal.ts, line 137 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuBWuLo8T4cX34Mknyo:-MuBWuLo8T4cX34Mknyp:bc1npjv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/types/proposal.ts#L137)):*
> ```XML
> }
> 
> export interface RequestChangeReasons {
> ```

As mentioned elsewhere already, this maybe should be renamed, and a link to the additional pdf might be added.
___
*[src/app/types/proposal.ts, line 154 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuBWTtZ0u2cDlz6RM-s:-MuBWTtZ0u2cDlz6RM-t:bga1gqi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/types/proposal.ts#L154)):*
> ```XML
> }
> 
> export interface PreviousTimeRequest {
> ```

This is more than a time request. Maybe a name like "TimeStatistics" might work?
___
*[src/app/proposal/general/progress-report/progress-report.component.html, line 285 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB-L9G8aWC5U2irOym:-MuB-L9G8aWC5U2irOyn:b-x25y3d) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.html#L285)):*
> ```HTML
>             type="submit"
>           >
>             Submit
> ```

If something is amiss in the form and you click on the submit button, nothing happens. I'd say there should be an error message near the button.

As yiu nicely pointed out in your TODO. :-)
___
*[src/app/proposal/general/progress-report/progress-report.component.ts, line 43 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MpqLVGE2rOWKl_5hpTJ:-MpuHlz74DJnMMM-ko7m:b122eah) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/proposal/general/progress-report/progress-report.component.ts#L43)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are you sure it is done -- I haven't seen such a check.
___
*[src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts, line 19 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB0O3m-5FLUzjVVS-f:-MuB0O3m-5FLUzjVVS-g:bjr700h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts#L19)):*
> ```XML
> export class ProposalProgressTableComponent implements OnInit {
>   @Input() proposal!: Proposal;
>   @Input() progressReport!: RequestChangeReasons;
> ```

I think the combination of "progressReport" and "RequestChangeReasons" looks odd. I guess RequestChangeReason has to be renamed (to ProgressReport ?). Note that (if supported) you could include a link to the additional pdf in this type.
___
*[src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts, line 34 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB5ieQ7FGlr_O4Ipby:-MuB5ieQ7FGlr_O4Ipbz:b-szv17z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts#L34)):*
> ```XML
>   wrongFileType = false;
>   nextSemester = getNextSemester();
>   whyTimeRequestChangedError = false;
> ```

It seems the value of this variable is never changed.

Also, arguably the variable name suggests a string value more than a boolean.
___
*[src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts, line 84 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB6U_o019tGWRxT_M-:-MuB6U_o019tGWRxT_M0:b4y18wz) ([raw file](https://github.com/saltastroops/web- [...]

2022-01-27 08:14 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/85)* status: 40 of 42 files reviewed, 20 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/util.ts, line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MppzfAk9xiLixbGs_3l:-MuFNcBT8x-hmUE7Q2pa:b-51nues) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/41a111712ee661b21ba9a21bc049e9c2212a312d/src/app/util.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You get the wrong year for January to April.
</blockquote></details>

This should be correct I subtract a year. for the first 4 month
___
*[src/app/utils.spec.ts, line 53 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAmHRsC-Eif9RFeSWZ:-MuL6hls1Jh3nh-YD0Jv:bry7ckz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/utils.spec.ts#L53)):*
> Also you might test that the semester transition happens at noon.
The method is date relate SO I couldn't  test for transition. 
___
*[src/app/proposal/general/proposal-progress/proposal-progress.component.ts, line 38 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAs5eABxQYq01fn4Yw:-MuFQgn5-uqntUpMNRcc:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hardcoded proposal code and semester
</blockquote></details>

Done.
___
*[src/app/proposal/general/proposal-progress/proposal-progress.component.ts, line 41 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAsVN-8t5EMNGNHyAn:-MuFR0AcCY6-_F7tEBZB:b7yj7qi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why don't you just say `this.progressReport = data` (or, if you prefer, `this.progressReport = {...data}`?
</blockquote></details>

yes. some data was comming from somewhere else forgot to fix
___
*[src/app/proposal/general/proposal-progress/proposal-progress.component.ts, line 56 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuAsyeE5AmX9cJwuZrC:-MuFRFQt2vG1nKlYBTXN:b-a0fkin) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress.component.ts#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this caught by the AuthenticationInterceptor service?
</blockquote></details>

yes it is
___
*[src/app/proposal/general/proposal-progress/requests-next-semester/previous-time-requests.component.html, line 4 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB87eg2oY_2eKKM4sb:-MuKv7fDBFxGQGGKslBv:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/requests-next-semester/previous-time-requests.component.html#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The requests for the next semester should not be handled in a component called previous-time-requests
</blockquote></details>

Done.
___
*[src/app/types/proposal.ts, line 154 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuBWTtZ0u2cDlz6RM-s:-MuL6N_r3j9wi3ik2NIn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/types/proposal.ts#L154)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is more than a time request. Maybe a name like "TimeStatistics" might work?
</blockquote></details>

Done.
___
*[src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts, line 19 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB0O3m-5FLUzjVVS-f:-MuPOZuD9XqqEoa2bdb5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/proposal-progress-table/proposal-progress-table.component.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the combination of "progressReport" and "RequestChangeReasons" looks odd. I guess RequestChangeReason has to be renamed (to ProgressReport ?). Note that (if supported) you could include a link to the additional pdf in this type.
</blockquote></details>

Done.
___
*[src/app/proposal/general/proposal-progress/requested-observing-conditions/requested-observing-conditions.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuB7P9p6jcBhSU7UqmD:-MuKO7Up9KQLCsxbbDNR:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/requested-observing-conditions/requested-observing-conditions.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no hardcoded value.
</blockquote></details>

Done.
___
*[src/app/proposal/general/proposal-progress/requests-next-semester/previous-time-requests.component.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/85#-MuBVLpp86gdSrp5qmHr:-MuKvNqE97tcSd1XbU-K:b202u6w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8e2d6498986d0f2d58e0ff25ab6c1c3aa6b6b7b2/src/app/proposal/general/proposal-progress/requests-next-semester/previous-time-requests.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this component actually used somewhere?
</blockquote></details>

no it is not


<!-- Sent from Reviewable.io -->

2022-11-09 10:31 UTC, closed without merging